package com.keetr.theupdate.network.fake

import com.keetr.theupdate.network.models.LatestHeadlinesApiModel

const val LatestHeadlinesResponse = """{
  "status": "ok",
  "total_hits": 10000,
  "page": 1,
  "total_pages": 334,
  "page_size": 30,
  "articles": [
    {
      "title": "Jokes fall flat in royal jewel heist starring Al Murray and Mel Giedroyc",
      "author": "Harrow Times Staff",
      "published_date": "2023-08-04 15:12:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.newsshopper.co.uk/news/23702302.review-royal-jewel-heist-starring-al-murray-mel-giedroyc/",
      "clean_url": "newsshopper.co.uk",
      "excerpt": "A self-professed ‘comic caper' set in Charles II's England, The Crown Jewels doesn't pretend to compete with the dramatic heists of modern…",
      "summary": "Joe Thomas as Tom Blood Jr, Aidan McArdle as Colonel Blood and _Neil Morrissey as Captain Perrot \n(Image: Hugo Glendenning)\n \n \n\n\n \n \n \n \n \n A self-professed ‘comic caper' set in Charles II's England, \nThe Crown Jewels\n doesn't pretend to compete with the dramatic heists of modern cinema that audiences have become so accustomed to. This is a far cry from Soderbergh's stylish \nOceans' Eleven,\n or \nThe Thomas Crown Affair\n (neither the 1968 nor 1999 version sadly).\n\n \n\n\n The criminals in question are more hapless than expert, and though caper they do – there's certainly lots of skipping about – the comedy is thin on the ground.",
      "rights": "harrowtimes.co.uk",
      "rank": 33128,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "Harrow Times Staff",
      "media": "https://www.harrowtimes.co.uk/resources/images/17076390/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "91b0700b669d0327c69793395c5736bd"
    },
    {
      "title": "Review: Royal jewel heist starring Al Murray and Mel Giedroyc",
      "author": "Richmond",
      "published_date": "2023-08-04 15:12:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.richmondandtwickenhamtimes.co.uk/news/23702302.review-royal-jewel-heist-starring-al-murray-mel-giedroyc",
      "clean_url": "richmondandtwickenhamtimes.co.uk",
      "excerpt": "A self-professed ‘comic caper' set in Charles II's England, The Crown Jewels doesn't pretend to compete with the dramatic heists of modern…",
      "summary": "The criminals in question are more hapless than expert, and though caper they do – there's certainly lots of skipping about – the comedy is thin on the ground.\n\nQuite unbelievably, the script was devised around a true historical event that most of us have never heard of. In 1671 Irish Parliamentarian – and general political agitator – Colonel Thomas Blood, with his son in tow, made a semi-successful attempt to steal the Crown jewels from the Tower of London, and damn near got away. Sounds exciting, doesn't it.",
      "rights": "richmondandtwickenhamtimes.co.uk",
      "rank": 131615,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "Richmond,Twickenham Times Staff",
      "media": "https://www.richmondandtwickenhamtimes.co.uk/resources/images/17076390/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "c5ecfb2c1588aea4ad8f5c0fa9dadd25"
    },
    {
      "title": "Grants for 'green' projects on offer to Keighley community groups",
      "author": "Alistair Shand",
      "published_date": "2023-08-04 15:12:20",
      "published_date_precision": "timezone unknown",
      "link": "https://www.keighleynews.co.uk/news/23702301.grants-green-projects-offer-keighley-groups/",
      "clean_url": "keighleynews.co.uk",
      "excerpt": "KEIGHLEY-district community groups are being invited to apply for grants of up to £50,000 for 'green' projects.",
      "summary": "Projects that encourage walking could benefit \n(Image: quest)\n \n \n\n\n \n \n \n \n \n KEIGHLEY-district community groups are being invited to apply for grants of up to £50,000 for 'green' projects.\n\n \n\n\n West Yorkshire mayor Tracy Brabin has launched the initiative.\n\n\n\n Beneficiaries could include projects that protect nature, improve people's wellbeing through walking and cycling, boost the energy efficiency of buildings or support the production of renewable energy.\n\n\n\n West Yorkshire Combined Authority will deliver the funding in partnership with the region's five local authorities, which will each issue grants according to their local net zero priorities.",
      "rights": "keighleynews.co.uk",
      "rank": 185010,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "Alistair Shand",
      "media": "https://www.keighleynews.co.uk/resources/images/16763754/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "8f30adffce18ab90d8502607cbd7e7d8"
    },
    {
      "title": "Galvalume Steel Coil Market Report, Key Players, Size, Share, Analysis 2023 and Forecast To 2029",
      "author": "Qyresearch Inc.",
      "published_date": "2023-08-04 15:12:05",
      "published_date_precision": "timezone unknown",
      "link": "https://www.openpr.com/news/3155661/galvalume-steel-coil-market-report-key-players-size-share",
      "clean_url": "openpr.com",
      "excerpt": "LOS ANGELES United States The global Galvalume Steel Coil market is carefully researched in the report while largely concentrating on top players and their business tactics geographical expansion…",
      "summary": "Galvalume Steel Coil Market Report, Key Players, Size, Share, Analysis 2023 and Forecast To 2029| Alliance Steel, Nirmala Avijaya Group\n\nhttps://www.qyresearch.com/sample/1608462\n\nhttps://www.qyresearch.com/customize/1608462\n\nLOS ANGELES, United States: The global Galvalume Steel Coil market is carefully researched in the report while largely concentrating on top players and their business tactics, geographical expansion, market segments, competitive landscape, manufacturing, and pricing and cost structures.",
      "rights": "openpr.com",
      "rank": 9387,
      "topic": "news",
      "country": "DE",
      "language": "en",
      "authors": "QYResearch Inc.",
      "media": "https://cdn.openpr.com/W/8/W804834023_g.jpg",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "b2b3382a90fe098088ed4aeb12bd9d35"
    },
    {
      "title": "Unparalleled Research on Corporate Service Robotics Market With Current and Future Growth Analysis by Forecast From 2023 to 2030",
      "author": "",
      "published_date": "2023-08-04 15:11:48",
      "published_date_precision": "timezone unknown",
      "link": "https://www.openpr.com/news/3155660/unparalleled-research-on-corporate-service-robotics-market",
      "clean_url": "openpr.com",
      "excerpt": "Worldwide Market Reports offers a 70 discount on Corporate Service Robotics Market Reports on Single User Access and Unlimited User Access Corporate Service Robotics Market 2023 Forecast to 2030…",
      "summary": "Unparalleled Research on Corporate Service Robotics Market With Current and Future Growth Analysis by Forecast From 2023 to 2030 |Boston Dynamics, BlueBotics SA, SoftBank Robotics\n\nCorporate Service Robotics Market\n\nhttps://www.worldwidemarketreports.com/sample/974627\n\nhttps://www.worldwidemarketreports.com/sample/974627\n\nhttps://www.worldwidemarketreports.com/quiry/974627\n\nhttps://www.worldwidemarketreports.com/promobuy/974627\n\nhttps://www.worldwidemarketreports.com\n\n\"Worldwide Market Reports offers a 70% discount on Corporate Service Robotics Market Reports on Single User Access and Unlimited User Access\"Corporate Service Robotics Market 2023 Forecast to 2030 research provides accurate economic, global, and country-level predictions and analyses.",
      "rights": "openpr.com",
      "rank": 9387,
      "topic": "news",
      "country": "DE",
      "language": "en",
      "authors": "",
      "media": "https://cdn.openpr.com/W/8/W804133533_g.jpg",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "b9080641e40b6e1b25c3efe7cdc556a2"
    },
    {
      "title": "Consumers told old Royal Mail stamps are fake in swap scheme, reports say",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:28",
      "published_date_precision": "timezone unknown",
      "link": "https://www.newsandstar.co.uk/news/national/23702295.consumers-told-old-royal-mail-stamps-fake-swap-scheme-reports-say/",
      "clean_url": "newsandstar.co.uk",
      "excerpt": "From August, regular stamps without a barcode became invalid as part of Royal Mail's plans to modernise the service.",
      "summary": "From August, regular stamps without a barcode were no longer valid but they can be exchanged for new barcoded versions, as part of Royal Mail's Stamp Swap Out scheme.\n\n\nPeople wishing to exchange their old stamps must fill out a form and send them to Royal Mail, where they will be swapped for new barcoded versions free of charge.\n \nBut some customers have found their old stamps are counterfeit or fraudulent, The Telegraph found.\n\n\nIf an invalid stamp is used, or the stamp is detected to be fraudulent or faulty, then the recipient will have to pay a fee in order to receive their post.",
      "rights": "newsandstar.co.uk",
      "rank": 27729,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.newsandstar.co.uk/resources/images/17076404/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "09f835b0dcdaded1ccb1a853428fdb9d"
    },
    {
      "title": "Consumers told old Royal Mail stamps are fake in swap scheme, reports say",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:28",
      "published_date_precision": "timezone unknown",
      "link": "https://www.penarthtimes.co.uk/news/national/23702295.consumers-told-old-royal-mail-stamps-fake-swap-scheme-reports-say/",
      "clean_url": "penarthtimes.co.uk",
      "excerpt": "From August, regular stamps without a barcode became invalid as part of Royal Mail's plans to modernise the service.",
      "summary": "From August, regular stamps without a barcode were no longer valid but they can be exchanged for new barcoded versions, as part of Royal Mail's Stamp Swap Out scheme.\n\n\nPeople wishing to exchange their old stamps must fill out a form and send them to Royal Mail, where they will be swapped for new barcoded versions free of charge.\n \nBut some customers have found their old stamps are counterfeit or fraudulent, The Telegraph found.\n\n\nIf an invalid stamp is used, or the stamp is detected to be fraudulent or faulty, then the recipient will have to pay a fee in order to receive their post.",
      "rights": "penarthtimes.co.uk",
      "rank": 406853,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.penarthtimes.co.uk/resources/images/17076404/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "2110121e52bd8b1d776f76c3b56fac05"
    },
    {
      "title": "Life for man who murdered boxer Tyson Fury's cousin",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:25",
      "published_date_precision": "timezone unknown",
      "link": "https://www.penarthtimes.co.uk/news/national/23702294.life-man-murdered-boxer-tyson-furys-cousin/",
      "clean_url": "penarthtimes.co.uk",
      "excerpt": "Liam O'Pray must serve life with a minimum 28 years for the knife killing of father-of-one Rico Burton",
      "summary": "Liam O'Pray, 22, used a lock-knife with a seven-inch blade to stab Rico Burton, 31, in the neck, almost severing his major carotid artery and causing massive blood loss.\n\n\nThe defendant, from Swinton, Salford, Greater Manchester, was found guilty of murder by a jury following a three-week trial last month at Manchester Crown Court, and on Friday was told he must serve a minimum of 28 years before parole.\n \nHe already had a conviction for carrying a knife in public before the murder.\n\n\nMr Burton's death prompted his boxing champion cousin to post an impassioned plea on social media about knife crime, declaring that 'this needs to stop'.",
      "rights": "penarthtimes.co.uk",
      "rank": 406853,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.penarthtimes.co.uk/resources/images/17076403/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "a92dfa3316a61ad27e8ff32f4d8ae793"
    },
    {
      "title": "Life for man who murdered boxer Tyson Fury's cousin",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:25",
      "published_date_precision": "timezone unknown",
      "link": "https://www.newsandstar.co.uk/news/national/23702294.life-man-murdered-boxer-tyson-furys-cousin/",
      "clean_url": "newsandstar.co.uk",
      "excerpt": "Liam O'Pray must serve life with a minimum 28 years for the knife killing of father-of-one Rico Burton",
      "summary": "Liam O'Pray, 22, used a lock-knife with a seven-inch blade to stab Rico Burton, 31, in the neck, almost severing his major carotid artery and causing massive blood loss.\n\n\nThe defendant, from Swinton, Salford, Greater Manchester, was found guilty of murder by a jury following a three-week trial last month at Manchester Crown Court, and on Friday was told he must serve a minimum of 28 years before parole.\n \nHe already had a conviction for carrying a knife in public before the murder.\n\n\nMr Burton's death prompted his boxing champion cousin to post an impassioned plea on social media about knife crime, declaring that 'this needs to stop'.",
      "rights": "newsandstar.co.uk",
      "rank": 27729,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.newsandstar.co.uk/resources/images/17076403/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "538010337571787102d7d122ac7ebabc"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.wiltshiretimes.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "wiltshiretimes.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "wiltshiretimes.co.uk",
      "rank": 108561,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.wiltshiretimes.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "2165ff070ef1a5e1e0ec1b8e7856e69a"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.bordertelegraph.com/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "bordertelegraph.com",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "bordertelegraph.com",
      "rank": 229488,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.bordertelegraph.com/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "ce6bdb84fc2760d5dab574106ea3ff06"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.harrowtimes.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "harrowtimes.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "harrowtimes.co.uk",
      "rank": 168003,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.harrowtimes.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "01b80961fc4ab6dc030c7b42dd012edc"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.thetottenhamindependent.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "thetottenhamindependent.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "thetottenhamindependent.co.uk",
      "rank": 493334,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.thetottenhamindependent.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "a09372f2be4928d1b875d3734c3b88bb"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.gazette-news.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "gazette-news.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "gazette-news.co.uk",
      "rank": 48246,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.gazette-news.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "3fa8dec326c9f67e282a2fe97ee581b4"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.tivysideadvertiser.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "tivysideadvertiser.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "tivysideadvertiser.co.uk",
      "rank": 278716,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.tivysideadvertiser.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "43660bf3b67129d4634ec51088ad4446"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.echo-news.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation",
      "clean_url": "echo-news.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "On Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.\n\nA 24-year-old man, who was wanted on a UK court warrant, was arrested and taken into custody in north London.\n\nFive people have been detained for questioning by Romanian officers for alleged human trafficking offences.",
      "rights": "echo-news.co.uk",
      "rank": 33817,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.echo-news.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "24e64a1c2c2bdd464f0f9b1ece84355d"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.richmondandtwickenhamtimes.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "richmondandtwickenhamtimes.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "richmondandtwickenhamtimes.co.uk",
      "rank": 131615,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.richmondandtwickenhamtimes.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "fb9ce402f933fe6490103e50cae51599"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.basingstokegazette.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "basingstokegazette.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "basingstokegazette.co.uk",
      "rank": 96106,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.basingstokegazette.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "f9d6cc9dd0ddc460be6c10b72a213030"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.penarthtimes.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "penarthtimes.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "penarthtimes.co.uk",
      "rank": 406853,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.penarthtimes.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "ed0433012c867b5f814a71e1ba878299"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.whtimes.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "whtimes.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "whtimes.co.uk",
      "rank": 136768,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.whtimes.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "aa78c14ebbf20b229f6995e544b3735f"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.keighleynews.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "keighleynews.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "keighleynews.co.uk",
      "rank": 185010,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.keighleynews.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "072d3f081fb77e90a7e166d1825bbc3a"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.dudleynews.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "dudleynews.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "dudleynews.co.uk",
      "rank": 252540,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.dudleynews.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "9b6877f3a2ff7a22767fe586a61aa2cc"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.yourlocalguardian.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "yourlocalguardian.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "yourlocalguardian.co.uk",
      "rank": 51428,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.yourlocalguardian.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "53e69232a4b36330c3cd4bbccd0de597"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.leaderlive.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation",
      "clean_url": "leaderlive.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "On Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.\n\nA 24-year-old man, who was wanted on a UK court warrant, was arrested and taken into custody in north London.\n\nFive people have been detained for questioning by Romanian officers for alleged human trafficking offences.",
      "rights": "leaderlive.co.uk",
      "rank": 77272,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.leaderlive.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "e8ed9782603da004b2dce05e1fb55d8b"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.barryanddistrictnews.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "barryanddistrictnews.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "barryanddistrictnews.co.uk",
      "rank": 253425,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.barryanddistrictnews.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "d4dbf2f514cbebb93f6be121f310971d"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.stourbridgenews.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "stourbridgenews.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "stourbridgenews.co.uk",
      "rank": 193431,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.stourbridgenews.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "343365f8436fbcda2e361e068c86b3c6"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.oxfordmail.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "oxfordmail.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "oxfordmail.co.uk",
      "rank": 15526,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.oxfordmail.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "854cef6f47541e7db115167856d773f4"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking ...",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.northwalespioneer.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation",
      "clean_url": "northwalespioneer.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "On Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.\n\nA 24-year-old man, who was wanted on a UK court warrant, was arrested and taken into custody in north London.\n\nFive people have been detained for questioning by Romanian officers for alleged human trafficking offences.",
      "rights": "northwalespioneer.co.uk",
      "rank": 288945,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.northwalespioneer.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "bd99dae7979bc5f15726c6226c09a5c0"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.wiltsglosstandard.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "wiltsglosstandard.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "wiltsglosstandard.co.uk",
      "rank": 150605,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.wiltsglosstandard.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "47db102fee5cbadd11b40d22a4243c31"
    },
    {
      "title": "Six held in Romania and London as part of human trafficking investigation",
      "author": "PA News Agency",
      "published_date": "2023-08-04 15:11:23",
      "published_date_precision": "timezone unknown",
      "link": "https://www.chesterstandard.co.uk/news/national/23702293.six-held-romania-london-part-human-trafficking-investigation/",
      "clean_url": "chesterstandard.co.uk",
      "excerpt": "The Metropolitan Police believe an organised crime network is using male recruiters to traffic women and force them into prostitution.",
      "summary": "A 24-year-old man, who was wanted on a UK court warrant, was arrested by the Metropolitan Police and is in custody in north London (Andrew Matthews/PA)\n \n \n\n\n \n \n \n \n \nSix people in London and Romania have been held as part of a police investigation into human trafficking using 'loverboy tactics' to lure women into prostitution.\n \n\n\nOn Friday morning, 133 officers took part in raids in the two countries and six people suspected of being victims of modern slavery were found in London.\n\n\nThe Metropolitan Police believe an organised crime network is using male recruiters in Romania to pretend to be boyfriends to potential victims before trafficking them to London for use in the sex trade.",
      "rights": "chesterstandard.co.uk",
      "rank": 134867,
      "topic": "news",
      "country": "GB",
      "language": "en",
      "authors": "PA News Agency",
      "media": "https://www.chesterstandard.co.uk/resources/images/16697859/?type=og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "08747fdc1c41680bfe48b5b7119d9e44"
    }
  ],
  "user_input": {
    "lang": [
      "en"
    ],
    "not_lang": null,
    "countries": null,
    "not_countries": null,
    "page": 1,
    "size": 30,
    "sources": null,
    "not_sources": [],
    "topic": null,
    "from": "2023-07-28 15:12:49"
  }
}"""