package com.keetr.theupdate.network

const val LatestHeadlinesResponse = """{
  "status": "ok",
  "total_hits": 10000,
  "page": 1,
  "total_pages": 200,
  "page_size": 50,
  "articles": [
    {
      "title": "صراع بين الزمالك والوحدة السعودي على ضم بن شرقي",
      "author": "اسامة حافظ",
      "published_date": "2023-07-14 22:54:34",
      "published_date_precision": "timezone unknown",
      "link": "https://www.vetogate.com/4930018",
      "clean_url": "vetogate.com",
      "excerpt": "دخل أشرف بن شرقي لاعب الجزيرة الإماراتي السابق ضمن حسابات ناديي الزمالك والوحدة السعودي خلال فترة الانتقالات الصيفية الحالية.",
      "summary": "الجمعة 14/يوليو/2023 - 10:54 م\n\n 7/14/2023 10:54:34 PM \n\n\n\n\n\n\n\n\nدخل أشرف بن شرقي لاعب الجزيرة الإماراتي السابق ضمن حسابات ناديي الزمالك والوحدة السعودي خلال فترة الانتقالات الصيفية الحالية.\nوكشفت قنوات الكاس القطرية أن ناديي الوحدة السعودي والزمالك يتنافسان بقوة للتعاقد مع أشرف بن شرقي في الصيف الحالي.\nوقال حساب قناة الكاس على موقع فيس بوك: نادي  الوحدة السعودي والزمالك المصري يتنافسان على التعاقد مع المغربي أشرف بن شرقي من أجل التعاقد معه خلال فترة الانتقالات الصيفية الحالية.\n \nوأعلن نادي الجزيرة الإماراتي، رحيل الدولي المغربي أشرف بن شرقي بشكل نهائي عن صفوف الفريق، بعد فسخ العقد بالتراضي.",
      "rights": "vetogate.com",
      "rank": 124730,
      "topic": "sport",
      "country": "EG",
      "language": "ar",
      "authors": "اسامة حافظ,فيتو",
      "media": "https://www.vetogate.com/UploadCache/libfiles/459/2/600x338o/942.jpg",
      "is_opinion": false,
      "twitter_account": "sync",
      "_score": null,
      "_id": "a67cc8045f488a0210f8292995d3ecfa"
    },
    {
      "title": "S'ka më Polici në veri pa KFOR-in e EULEX-in",
      "author": "Zëri",
      "published_date": "2023-07-14 22:54:17",
      "published_date_precision": "timezone unknown",
      "link": "http://zeri.info/aktuale/499004/ska-me-polici-ne-veri-pa-kfor-in-e-eulex-in/",
      "clean_url": "zeri.info",
      "excerpt": "Përcjellje, asistim, e arrestime në veri, Policia e Kosovës s`mund të bëjë kokë në vete më. Të paktën jo pa marrë aminin e misionit paqeruajtës, e atij evropian për sundim...",
      "summary": "Aktuale\n \nJuly 14, 2023 - 22:54\n \n \nPërcjellje, asistim, e arrestime në veri, Policia e Kosovës s`mund të bëjë kokë në vete më.\n \nTë paktën jo pa marrë aminin e misionit paqeruajtës, e atij evropian për sundim të ligjit.\n \nKjo është njëra nga pikat për shtensionim të veriut, nga dakordimi i së martës në Bratisllavë përfaqësuesi evropian i dialogut Miroslav Lajçak e kryenegociatori kosovar Besnik Bislimi.\n \nPër Institutin Kosovar të Drejtësisë, pavarësisht lëvizjes para për de-eskalim, është prapakthim.",
      "rights": "zeri.info",
      "rank": 362995,
      "topic": "news",
      "country": "XK",
      "language": "sq",
      "authors": "Zëri",
      "media": "http://zeri.info/uploads/zeri.info/images/2023/June/21/auto_kfori-policia-veri1687337717.jpg",
      "is_opinion": false,
      "twitter_account": "@gazetazeri",
      "_score": null,
      "_id": "8002fb9dc4bdf2236591a9b2d832a296"
    },
    {
      "title": "مصطفى بكري: مفاجأة للمصريين من القيادة السياسية قريبا",
      "author": "",
      "published_date": "2023-07-14 22:54:15",
      "published_date_precision": "timezone unknown",
      "link": "https://elbashayer.com/3199231/%d9%85%d8%b5%d8%b7%d9%81%d9%89-%d8%a8%d9%83%d8%b1%d9%8a-%d9%85%d9%81%d8%a7%d8%ac%d8%a3%d8%a9-%d9%84%d9%84%d9%85%d8%b5%d8%b1%d9%8a%d9%8a%d9%86-%d9%85%d9%86-%d8%a7%d9%84%d9%82%d9%8a%d8%a7%d8%af%d8%a9",
      "clean_url": "elbashayer.com",
      "excerpt": null,
      "summary": "أكّد الإعلامي مصطفى بكري، قدرة الدولة المصرية على تجاوز الآثار الناجمة عن الأزمة الاقتصادية العالمية، رغم الحملات الممنهجة للنيل من مصر بالتزامن مع قرب انطلاق الانتخابات الرئاسية في 2024. أضاف مصطفى بكري، خلال برنامج «حقائق وأسرار» على قناة صدى البلد، أنّ المواطن المصري له الحرية في اختيار من يرى أنه يمثله ويعبر عن تطلعاته، لكن […]",
      "rights": "elbashayer.com",
      "rank": 743896,
      "topic": "news",
      "country": "EG",
      "language": "ar",
      "authors": "",
      "media": "https://elbashayer.com/elbashayer/uploads/2023/07/elbashayer-2023-07-14_064341.jpg",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "b75f5c09a8f98dcebb987e989112f879"
    },
    {
      "title": "Ordenan intervención de Partido Justicialista en Jujuy, Argentina",
      "author": "Prensa Latina",
      "published_date": "2023-07-14 22:54:15",
      "published_date_precision": "timezone unknown",
      "link": "https://www.la-epoca.com.bo/2023/07/14/ordenan-intervencion-de-partido-justicialista-en-jujuy-argentina/",
      "clean_url": "la-epoca.com.bo",
      "excerpt": "Buenos Aires-. El presidente de Argentina y del Partido Justicialista (PJ), Alberto Fernández, ordenó hoy intervenir por 360 días la representación de esa organización política en la provincia de…",
      "summary": "Buenos Aires-. El presidente de Argentina y del Partido Justicialista (PJ), Alberto Fernández, ordenó hoy intervenir por 360 días la representación de esa organización política en la provincia de Jujuy por violaciones cometidas por varios de sus miembros.\nMediante una resolución, el jefe de Estado comunicó que el abogado Gustavo Adolfo Méndez y el ministro de Seguridad, Aníbal Fernández, ejercerán de manera conjunta las facultades inherentes a los órganos de la agrupación en ese distrito y realizarán los actos necesarios para normalizar el PJ en ese lugar.",
      "rights": "la-epoca.com.bo",
      "rank": 899261,
      "topic": "news",
      "country": "BO",
      "language": "es",
      "authors": "Fabián Dávila Torrez,Jairo Corbalan,Maria Isabel Còrdoba Moreno,Patricia,Prensa Latina,Renato Martinelli",
      "media": "https://www.la-epoca.com.bo/wp-content/uploads/2019/10/alberto_fernandez_1569426187.jpg",
      "is_opinion": false,
      "twitter_account": "@laepocabo",
      "_score": null,
      "_id": "33b90ba4dfa279d0e6ed4bb985140296"
    },
    {
      "title": "বর্ষার ছড়া",
      "author": "",
      "published_date": "2023-07-14 22:54:11",
      "published_date_precision": "timezone unknown",
      "link": "https://www.deshrupantor.com/ouside-calssroom/2023/07/15/438730",
      "clean_url": "deshrupantor.com",
      "excerpt": null,
      "summary": "খুশির মজা সমর পাল বৃষ্টি ভেজা সবুজ ঘাসে আলতো ছোঁয়া পায় খুকুমণি বেড়ায় ঘুরে এদিক ওদিক চায়। বাগানজুড়ে ফুলের মেলায় প্রজাপতির খেলা দেখতে দেখতে খুকুমণির কাটলো সকালবেলা! আপু এসে বলল খুকু তুমি ভীষণ ভালো তোমার জন্য সূর্যিমামা ছড়ায়",
      "rights": "Copyright: (C) deshrupantor",
      "rank": 905696,
      "topic": "news",
      "country": "BD",
      "language": "bn",
      "authors": "",
      "media": "",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "d179b1d85fb53a8402a1608f668cacd8"
    },
    {
      "title": "Malaga Financial Corporation Reports Increased Earnings for the First Six Months of 2023",
      "author": "globenewswire",
      "published_date": "2023-07-14 22:54:00",
      "published_date_precision": "timezone unknown",
      "link": "https://www.wallstreet-online.de/nachricht/17138603-malaga-financial-corporation-reports-increased-earnings-for-the-first-six-months-of-2023",
      "clean_url": "wallstreet-online.de",
      "excerpt": "14.07.2023 - PALOS VERDES ESTATES, Calif., July 14, 2023 (GLOBE NEWSWIRE) - Malaga Financial Corporation 'Company' (OTCPink:MLGF), the parent company of Malaga Bank FSB, today reported that net income for the six months ended June 30, 2023 was ${'$'}11,469,000 ... Seite 1",
      "summary": "PALOS VERDES ESTATES, Calif., July 14, 2023 (GLOBE NEWSWIRE) -- Malaga Financial Corporation 'Company' (OTCPink:MLGF), the parent company of Malaga Bank FSB, today reported that\n net income for the six months ended June 30, 2023 was ${'$'}11,469,000 (${'$'}1.34 basic and fully diluted earnings per share) compared to ${'$'}9,774,000 (${'$'}1.14 basic and fully diluted earnings per share, as\n adjusted for the stock",
      "rights": "wallstreet-online.de",
      "rank": 17657,
      "topic": "finance",
      "country": "DE",
      "language": "en",
      "authors": "globenewswire",
      "media": "https://assets.wallstreet-online.de/_media/6/source1280/size_645/globenewswire-1280.png",
      "is_opinion": false,
      "twitter_account": "@wotwitt",
      "_score": null,
      "_id": "70a7c344d6609fbf89f233507b9316dc"
    },
    {
      "title": "Alcaraz: Vjerujem da mogu pobijediti Đokovića",
      "author": "",
      "published_date": "2023-07-14 22:54:00",
      "published_date_precision": "timezone unknown",
      "link": "https://bljesak.info/sport/ostali-sportovi/alcaraz-vjerujem-da-mogu-pobijediti-dokovica/426449",
      "clean_url": "bljesak.info",
      "excerpt": "Carlos Alcaraz bit će u prilici za svoj drugi Grand Slam naslov. Pozornica je spremna za nedjelju u finalu Wimbledona, kada će se s druge strane mreže biti Novak Đoković. Bit će to repriza polufinala…",
      "summary": "Carlos Alcaraz bit će u prilici za svoj drugi Grand Slam naslov. Pozornica je spremna za nedjelju u finalu Wimbledona, kada će se s druge strane mreže biti Novak Đoković. Bit će to repriza polufinala Roland Garrosa od ove godine.\n \n\n\n\n\n\n\n\n\n\n\n \n\n\n\nFoto: Carlos Alcaraz/Twitter / Carlos Alcaraz\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\nTekst članka se nastavlja ispod banera\n\"Znam da je Novak Đoković nepobjediv na središnjem terenu Wimbledonu od 2013. godine, ali vjerujem u sebe\", rekao je prvi tenisač svijeta Carlos Alcaraz prije međusobnog nedjeljnog finala u Wimbledonu.",
      "rights": "bljesak.info",
      "rank": 143110,
      "topic": "news",
      "country": "BA",
      "language": "hr",
      "authors": "",
      "media": "https://storage.bljesak.info/article/426449/800x550/alca-raz.jpg",
      "is_opinion": false,
      "twitter_account": "@bljesak",
      "_score": null,
      "_id": "950bdb418e3d55bc8534c5605901b698"
    },
    {
      "title": "Alcaraz irrumpe en la final",
      "author": "",
      "published_date": "2023-07-14 22:53:59",
      "published_date_precision": "timezone unknown",
      "link": "https://www.larepublica.ec/blog/2023/07/14/alcaraz-irrumpe-en-la-final",
      "clean_url": "larepublica.ec",
      "excerpt": "Con la fuerza de un transatlántico y con la tranquilidad y la calma de un samurai, Carlos Alcaraz irrumpe en la final de Wimbledon. Derrotó con solvencia al ruso Daniil Medvedev (6-3, 6-3 y 6-3) y sigue los pasos de Manolo Santana (1966) y Rafael Nadal (cinco finales consecutivas entre 2006 y 2011) como españoles",
      "summary": "Con la fuerza de un transatlántico y con la tranquilidad y la calma de un samurai, Carlos Alcaraz irrumpe en la final de Wimbledon. Derrotó con solvencia al ruso Daniil Medvedev (6-3, 6-3 y 6-3) \n[...]\n\nThe post \nAlcaraz irrumpe en la final\n first appeared on \nLa República EC\n.",
      "rights": "larepublica.ec",
      "rank": 128709,
      "topic": "news",
      "country": "EC",
      "language": "es",
      "authors": "",
      "media": "https://www.larepublica.ec/wp-content/uploads/2023/07/alcaraz-finalista.jpg",
      "is_opinion": false,
      "twitter_account": "@larepublica_ec",
      "_score": null,
      "_id": "cbaf5a9c2a1f2d8158ef6e74772f7e13"
    },
    {
      "title": "Người Do Thái vay 1 USD, ngân hàng bỗng dưng bị hụt một khoản tiền lớn: Tư duy của người có tiền không hề đơn giản",
      "author": "Thùy Anh",
      "published_date": "2023-07-14 22:53:59",
      "published_date_precision": "timezone unknown",
      "link": "https://soha.vn/nguoi-do-thai-vay-1-usd-ngan-hang-bong-dung-bi-hut-mot-khoan-tien-lon-tu-duy-cua-nguoi-co-tien-khong-he-don-gian-20230713213839514.htm",
      "clean_url": "soha.vn",
      "excerpt": "Người Do Thái quan niệm rằng trí tuệ mới chính là của cải. Nhờ vậy, họ có cách giáo dục và tư duy khác biệt hoàn toàn so với số đông còn lại.",
      "summary": "Cách vay tiền lạ đời\n\nMột bước vào một ở New York, đi đến bộ phận cho vay, và ngồi xuống một cách nghiêm túc.\n\n\"Có chuyện gì vậy, thưa ông?\", người quản lý cho vay hỏi. Đồng thời anh cũng quan sát người đàn ông này và thấy rằng ông ta đang khoác trên mình bộ vest sang trọng, giày da cao cấp, đồng hồ đắt tiền và kẹp cà vạt nạm ngọc.\n\n- Tôi muốn vay một ít tiền\n\n- Được rồi, ông muốn vay bao nhiêu?\n\n- Một USD\n\n- Chỉ một USD?\n\n- Đúng vậy, chỉ cần vay một USD, có được không?\n\n- Đương nhiên, chỉ cần có bảo đảm, ông muốn thêm cũng không thành vấn đề\n\nKế tiếp đó, lấy ra một đống cổ phiếu, từ trong chiếc ví sang trọng của mình và đặt nó trên bàn của người quản lý:\n\n- Tổng cộng là 500.",
      "rights": "soha.vn",
      "rank": 34758,
      "topic": "news",
      "country": "VN",
      "language": "vi",
      "authors": "Thùy Anh,VCCorp.vn",
      "media": "https://sohanews.sohacdn.com/zoom/600_315/160588918557773824/2023/7/13/photo1689258972588-1689258972705128170213.jpg",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "cd0d1e2f01f951196b16355220d14786"
    },
    {
      "title": "打掉犯罪团伙85个 公安部介绍打击治理粤港澳海上跨境走私专项行动-中新网视频",
      "author": "chinanews",
      "published_date": "2023-07-14 22:53:52",
      "published_date_precision": "timezone unknown",
      "link": "http://www.chinanews.com/shipin/cns-d/2023/07-14/news964771.shtml",
      "clean_url": "chinanews.com",
      "excerpt": "打掉犯罪团伙85个 公安部介绍打击治理粤港澳海上跨境走私专项行动 发布时间：2023年07月14日 22:53 来源：中国新闻网 7月14日，公安部召开新闻发布会，通报依法严厉打击走私违法犯罪的工作措施及成效。海关总署缉私局副局长李云龙介绍，&#",
      "summary": "打掉犯罪团伙85个 公安部介绍打击治理粤港澳海上跨境走私专项行动\n \n \n 发布时间：2023年07月14日 22:53     来源：中国新闻网\n \n \n \n \n \n　　7月14日，公安部召开新闻发布会，通报依法严厉打击走私违法犯罪的工作措施及成效。海关总署缉私局副局长李云龙介绍，从2021年10月到2022年12月，海关总署、公安部会同国家移民局、中国海警局、广东省人民政府以及全国打私办联合开展了两轮打击治理粤港澳海上跨境走私专项行动。在两轮联合行动中，缉私部门累计出动缉私艇3637艘次，侦办走私及其关联犯罪案件1589起，案值超过了71个亿，打掉了犯罪团伙85个，抓获走私犯罪嫌疑人958名。\n \n　　李云龙表示，规模化、暴力化的走私势头得到遏制，海上执法环境、治安形势明显好转。(李佳励）\n \n责任编辑：【卞立群】\n \n版权声明：中新视频版权属中新社所有，未经书面许可的使用行为，本社将依法追究其法律责任。",
      "rights": "chinanews.com",
      "rank": 993,
      "topic": "news",
      "country": "CN",
      "language": "cn",
      "authors": "chinanews",
      "media": "https://poss-videocloud.cns.com.cn/oss/2023/07/14/chinanews/MEIZI_YUNSHI/uploadImage/c8ad5bf18fb74b4b8225d6aae0af18dd_big.jpg",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "e5bb27048bbb2b0824c895342c4946f0"
    },
    {
      "title": "La UEFA sancionó al Barcelona",
      "author": "",
      "published_date": "2023-07-14 22:53:43",
      "published_date_precision": "timezone unknown",
      "link": "https://guatefutbol.com/2023/07/14/la-uefa-sanciono-al-barcelona",
      "clean_url": "guatefutbol.com",
      "excerpt": "ESPAÑA – Los culés no hicieron bien las declaraciones de sus beneficios. La Primera Sala del CFCB, presidida por Sunil Gulati, concluyó la evaluación de los ejercicios 2019, 2020, 2021 y 2022, sobre la base del Reglamento de Licencias de clubes y Fair Play Financiero (FFP), en el que interpuso varias multas, incluyendo al FC",
      "summary": "ESPAÑA – Los culés no hicieron bien las declaraciones de sus beneficios. La Primera Sala del CFCB, presidida por Sunil Gulati, concluyó la evaluación de los ejercicios 2019, 2020, 2021 y 2022, sobre la base del Reglamento de Licencias de clubes y Fair Play Financiero (FFP), en el que interpuso varias multas, incluyendo al FC […]\n\n\nThe post \nLa UEFA sancionó al Barcelona\n first appeared on \nGuatefutbol.com\n.",
      "rights": "guatefutbol.com",
      "rank": 919525,
      "topic": "news",
      "country": "GT",
      "language": "es",
      "authors": "",
      "media": "https://guatefutbol.com/wp-content/uploads/2023/07/Joan-Laporta-Barcelona.jpg",
      "is_opinion": false,
      "twitter_account": "@guatefut",
      "_score": null,
      "_id": "7f259aab8ebedc50dedb37d163f62647"
    },
    {
      "title": "تفاصيل المران الأول للأهلي بعد رباعية الزمالك",
      "author": "عبدالحكيم أبوعلم",
      "published_date": "2023-07-14 22:53:26",
      "published_date_precision": "timezone unknown",
      "link": "https://www.elbalad.news/5844776",
      "clean_url": "elbalad.news",
      "excerpt": "أدى الفريق الأول لكرة القدم بالنادي الأهلي مرانه مساء اليوم على ملعب التتش، استعدادًا لمباراة المقاولون العرب، المقرر لها مساء الأحد المقبل ضمن منافسات الجولة الـ٣٤ لبطولة الدوري الممتاز. وعقد مارسيل…",
      "summary": "أدى الفريق الأول لكرة القدم بالنادي الأهلي مرانه مساء اليوم على ملعب التتش، استعدادًا لمباراة المقاولون العرب، المقرر لها مساء الأحد المقبل ضمن منافسات الجولة الـ٣٤ لبطولة الدوري الممتاز.\n\nوعقد مارسيل كولر، المدير الفني للفريق، محاضرة مع اللاعبين قبل انطلاق المران، للحديث عن الجوانب الفنية.\n\nوخاض اللاعبون الذين شاركوا أمس أمام الزمالك تدريبات استشفائية للتخلص من الإجهاد العضلي، فيما أدى باقي اللاعبين المران كاملًا، والذي اشتمل على جزءين بدني وخططي.\n\nوقاد ميشيل يانكون مدرب الحراس، تدريبات الرباعي، علي لطفي ومصطفى شوبير وحمزة علاء ومصطفى مخلوف رباعي حراسة المرمى.",
      "rights": "elbalad.news",
      "rank": 69336,
      "topic": "news",
      "country": "LB",
      "language": "ar",
      "authors": "صدى البلد,عبدالحكيم أبوعلم",
      "media": "https://www.elbalad.news/UploadCache/libfiles/1014/1/600x338o/355.jpg",
      "is_opinion": false,
      "twitter_account": "@ElBaladOfficial",
      "_score": null,
      "_id": "fb25ad24307597a893a801c67e28baa0"
    },
    {
      "title": "بعد خسارة الزمالك.. عمرو أديب: \"النادي بيقع وإكرام الميت دفنه\"",
      "author": "هدى عبدالرازق",
      "published_date": "2023-07-14 22:53:18",
      "published_date_precision": "timezone unknown",
      "link": "https://www.elfagr.org/4727899",
      "clean_url": "elfagr.org",
      "excerpt": "عقب الإعلامي عمرو أديب، على نتيجة مباراة الاهلي والزمالك بالدوري المصري أمس، مشيرا إلى أن نتيجة المباراة لم تكن مفاجأة، ولكن عدد الأهداف كان كتير وتقيل .",
      "summary": "عمرو أديب\n\n\n\n \n\n\nعقب الإعلامي عمرو أديب، على نتيجة مباراة \"الاهلي والزمالك\" بالدوري المصري أمس، مشيرا إلى أن نتيجة المباراة لم تكن مفاجأة، ولكن عدد الأهداف كان \"كتير وتقيل\".\nمستوى نادي الزمالك\nوقال أديب، خلال برنامج \"الحكاية\" المذاع عبر فضائية \"إم بي سي مصر\"، مساء الجمعة، \"في فرق بين اللاعب اللي أمه أخدته من إيده وقالته امضي للأهلي.. حسين الشحات إمبارح جاب جونين حلوين\"، لافتا إلى أن أداء حارس مرمى الزمالك كان سيىء للغاية.\nوأضاف، \"الزمالك اتغلب عشان سيىء، منتظر إيه من فرقة ثلثها وهو بيلعب بيفكر هيهرب من الزمالك ويروح الأهلي إزاي، والتلت التاني بيفكر هيروح بيراميدز وفيوتشر إزاي.",
      "rights": "elfagr.org",
      "rank": 182486,
      "topic": "news",
      "country": "EG",
      "language": "ar",
      "authors": "بوابة الفجر,هدى عبدالرازق",
      "media": "https://www.elfagr.org/UploadCache/libfiles/510/1/600x338o/509.png",
      "is_opinion": false,
      "twitter_account": "@fagr24_",
      "_score": null,
      "_id": "c637b802caba388d0e1a2ce700e10bd3"
    },
    {
      "title": "ترتيب الدوري المصري، هبوط غزل المحلة وأسوان وبقاء الداخلية بالممتاز",
      "author": "محمود درويش",
      "published_date": "2023-07-14 22:53:14",
      "published_date_precision": "timezone unknown",
      "link": "https://www.vetogate.com/4930021",
      "clean_url": "vetogate.com",
      "excerpt": "ترتيب الدوري المصري، هبط فريقا أسوان وغزل المحلة رسميا لمرافقة حرس الحدود إلي دوري المحترفين بعد احتلالهم المراكز الثلاثة الأخيرة في الدوري المصري الممتاز .",
      "summary": "الجمعة 14/يوليو/2023 - 10:53 م\n\n 7/14/2023 10:53:14 PM \n\n\n\n\n\n\n\n\nترتيب الدوري المصري\n، هبط فريقا أسوان و\nغزل المحلة\n رسميا لمرافقة حرس الحدود إلي دوري المحترفين، بعد احتلالهم المراكز الثلاثة الأخيرة في \nالدوري المصري الممتاز\n، فيما نجح الداخلية في البقاء بالممتاز.\nوانتهت مباريات اليوم الأول في الجولة الـ 34 والأخيرة، بفوز بيراميدز علي طلائع الجيش 4-2، والبنك الأهلي علي فيوتشر 1-0، وفوز الداخلية علي أسوان 4-2، وفوز حرس الحدود علي غزل المحلة 2-1.\nوبهذه النتائج هبط أسوان وغزل المحلة رسميا، وضمن الزمالك رسميا احتلاله المركز الثالث في جدول ترتيب الدوري المصري الممتاز، قبل لقاء الأبيض أمام فاركو الأحد، في ختام مبارياته بالدوري المصري ، بعد خسارة فيوتشر أمام البنك الأهلي.",
      "rights": "vetogate.com",
      "rank": 124730,
      "topic": "sport",
      "country": "EG",
      "language": "ar",
      "authors": "محمود درويش",
      "media": "https://www.vetogate.com/UploadCache/libfiles/461/8/600x338o/562.jpg",
      "is_opinion": false,
      "twitter_account": "sync",
      "_score": null,
      "_id": "f986bad60876de407a6f980506ba5cf9"
    },
    {
      "title": "Haedar Nashir dan Prabowo Subianto Tak Bahas Politik, Bicara Rudal Buatan UAD Hingga Konstitusi",
      "author": "Pt. Viva Media Baru",
      "published_date": "2023-07-14 22:53:07",
      "published_date_precision": "timezone unknown",
      "link": "https://www.viva.co.id/berita/nasional/1618243-haedar-nashir-dan-prabowo-subianto-tak-bahas-politik-bicara-rudal-buatan-uad-hingga-konstitusi",
      "clean_url": "viva.co.id",
      "excerpt": "Menteri Pertahanan (Menhan), Prabowo Subianto, mengunjungi Kampus 4 Universitas Ahmad Dahlan (UAD) dan bertemu dengan Ketua Umum PP Muhammadiyah, Haedar Nashir, Jumat ini",
      "summary": "Yogyakarta\n – Menteri Pertahanan (Menhan), \nPrabowo Subianto\n, mengunjungi Kampus 4 \nUniversitas Ahmad Dahlan\n (UAD) dan bertemu dengan Ketua Umum PP \nMuhammadiyah\n, \nHaedar Nashir\n, Jumat 14 Juli 2023. \n \nDalam pertemuan itu, Haedar ditemani oleh Sekretaris Umum PP Muhammadiyah Prof Abdul Mu'ti dan Rektor UAD Muchlas MT.\nBegitu tiba di UAD, Prabowo langsung ditemui Haedar Nashir di lantai 10 Gedung Utama Kampus 4 UAD. Pertemuan antara Prabowo dan Haedar Nashir ini dilakukan secara tertutup.\n\n\nHaedar menjelaskan, pertemuan antara Muhammadiyah dengan Prabowo ini tidak membahas masalah \npolitik\n.",
      "rights": "viva.co.id",
      "rank": 24783,
      "topic": "news",
      "country": "ID",
      "language": "id",
      "authors": "Agus Rahmat,PT. VIVA MEDIA BARU,VIVA",
      "media": "https://thumb.viva.co.id/media/frontend/thumbs3/2023/07/14/64b16ddbeae96-ketum-pp-muhammadiyah-haedar-nashir-prabowo-subianto-dan-abdul-mu-ti_665_374.jpeg",
      "is_opinion": false,
      "twitter_account": "@VIVAcoid",
      "_score": null,
      "_id": "f7264063e258b4418e2e7a4407870481"
    },
    {
      "title": "ট্রাকের চাপায় নারীসহ অটোরিকশার তিন যাত্রী নিহত",
      "author": "মধুপুর  প্রতিনিধি",
      "published_date": "2023-07-14 22:53:01",
      "published_date_precision": "full",
      "link": "https://www.jugantor.com/country-news/696128/ট্রাকের-চাপায়-নারীসহ-অটোরিকশার-তিন-যাত্রী-নিহত",
      "clean_url": "jugantor.com",
      "excerpt": "টাঙ্গাইলের ধনবাড়ীতে ট্রাকের চাপায় অটোরিকশার তিন যাত্রী নিহত হয়েছেন। এর মধ্যে ঘটনাস্থলেই নিহত হয়েছেন দুইজন। আর হাসপাতালে নেওয়ার পর মারা গেছেন আরও একজন। এ ঘটনায় শিশুসহ আহত চারজনকে পাঠানো হয়েছে ময়মনসিংহ মেডিকেল কলেজ হাসপাতালে।",
      "summary": "টাঙ্গাইলের ধনবাড়ীতে ট্রাকের চাপায় অটোরিকশার তিন যাত্রী নিহত হয়েছেন। এর মধ্যে ঘটনাস্থলেই নিহত হয়েছেন দুইজন। আর হাসপাতালে নেওয়ার পর মারা গেছেন আরও একজন। এ ঘটনায় শিশুসহ আহত চারজনকে পাঠানো হয়েছে ময়মনসিংহ মেডিকেল কলেজ হাসপাতালে।",
      "rights": "Copyright 2023 https://www.jugantor.com",
      "rank": 105696,
      "topic": "news",
      "country": "BD",
      "language": "bn",
      "authors": "মধুপুর  প্রতিনিধি",
      "media": "https://fbshare.jugantor.com/fb_share?img=image-696128-1689375176.jpg",
      "is_opinion": false,
      "twitter_account": "@JUGANTOR",
      "_score": null,
      "_id": "aefbff6c1e259b96dbcfce3d659954a3"
    },
    {
      "title": "Sharks partner up with leading PNG Brand",
      "author": "",
      "published_date": "2023-07-14 22:53:00",
      "published_date_precision": "timezone unknown",
      "link": "https://www.looppng.com/sport/sharks-partner-leading-png-brand-121496",
      "clean_url": "looppng.com",
      "excerpt": "The major sponsor of the four-time national PNG champions the Lae Snax Tigers and a trusted and reputable company founded in 1972, the Lae Biscuits branding will appear on the back of the Sharks NRL…",
      "summary": "As stated by Sharks CEO Dino Mezzatesta, this association with Lae Biscuits is a ground breaking partnership and is set to be of great benefit to both organisations.\n\n\n'The Lae Biscuit Company have been long time supporters of rugby league in PNG and we thank Ian Chow and Lae Biscuits for considering the Sharks as a viable partner as they look to spread their wings into the Australian market,' Mezzatesta began.\n\n\n'The Sharks trialled in PNG in 2020 and were exceptionally well received, with this partnership further cementing our relationship with the only country in the world where rugby league is the national sport.",
      "rights": "looppng.com",
      "rank": 230313,
      "topic": "news",
      "country": "PG",
      "language": "en",
      "authors": "",
      "media": "https://looppacificassets.s3.amazonaws.com/styles/no_watermark/s3/thumbnails/image/20230714_225136_0000.png?itok=GNiEYxmb",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "853c0b250be2feb5861ca21070911061"
    },
    {
      "title": "Rentokil Initial (OTCMKTS:RTOKY) Shares Cross Above 200 Day Moving Average of ${'$'}35.34",
      "author": "Amber O'Connor",
      "published_date": "2023-07-14 22:52:47",
      "published_date_precision": "full",
      "link": "https://www.dispatchtribunal.com/2023/07/14/rentokil-initial-otcmktsrtoky-shares-cross-above-200-day-moving-average-of-35-34.html",
      "clean_url": "dispatchtribunal.com",
      "excerpt": "Rentokil Initial plc (OTCMKTS:RTOKY – Get Free Report) shares passed above its two hundred day moving average during trading on Wednesday . The stock has a two hundred day moving average of ${'$'}35.34 and traded as high as ${'$'}39.14. Rentokil Initial shares last traded at ${'$'}39.13, with a volume of 130,580 shares traded. Rentokil Initial […]",
      "summary": "Rentokil Initial plc (OTCMKTS:RTOKY – Get Free Report) shares passed above its two hundred day moving average during trading on Wednesday . The stock has a two hundred day moving average of ${'$'}35.34 and traded as high as ${'$'}39.14. Rentokil Initial shares last traded at ${'$'}39.13, with a volume of 130,580 shares traded. Rentokil Initial […]",
      "rights": "dispatchtribunal.com",
      "rank": 671423,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Amber O'Connor",
      "media": "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/rentokil-initial-plc-logo.jpg&w=240&h=240&zc=2",
      "is_opinion": false,
      "twitter_account": "@RatingsNetwork",
      "_score": null,
      "_id": "771af65623db8ce20efaa0a7769e2e8f"
    },
    {
      "title": "1,615 Shares in Air Products and Chemicals, Inc. (NYSE:APD) Bought by Oak Thistle LLC",
      "author": "Jeff Wilder",
      "published_date": "2023-07-14 22:52:44",
      "published_date_precision": "timezone unknown",
      "link": "https://www.dailypolitical.com/2023/07/14/1615-shares-in-air-products-and-chemicals-inc-nyseapd-bought-by-oak-thistle-llc.html",
      "clean_url": "dailypolitical.com",
      "excerpt": "Oak Thistle LLC bought a new position in shares of Air Products and Chemicals, Inc. (NYSE:APD – Free Report) during the first quarter, HoldingsChannel.com reports. The institutional investor bought…",
      "summary": "Oak Thistle LLC bought a new position in shares of Air Products and Chemicals, Inc. (\nNYSE:APD\n – \nFree Report\n) during the first quarter, \nHoldingsChannel.com\n reports. The institutional investor bought 1,615 shares of the basic materials company's stock, valued at approximately ${'$'}464,000. \n\n\nOther institutional investors have also added to or reduced their stakes in the company. Armstrong Advisory Group Inc. acquired a new position in Air Products and Chemicals during the fourth quarter worth ${'$'}27,000.",
      "rights": "dailypolitical.com",
      "rank": 793836,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Jeff Wilder",
      "media": "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/air-products--chemicals-inc-logo.jpg&w=240&h=240&zc=2",
      "is_opinion": false,
      "twitter_account": "@MarketBeatCom",
      "_score": null,
      "_id": "4b752fbc528dd4c9eec9a35653cd9c08"
    },
    {
      "title": "Analog Devices, Inc. (NASDAQ:ADI) Shares Bought by Baker Chad R",
      "author": "Patrick Bannon",
      "published_date": "2023-07-14 22:52:44",
      "published_date_precision": "timezone unknown",
      "link": "https://www.dailypolitical.com/2023/07/14/analog-devices-inc-nasdaqadi-shares-bought-by-baker-chad-r.html",
      "clean_url": "dailypolitical.com",
      "excerpt": "Baker Chad R increased its holdings in shares of Analog Devices, Inc. (NASDAQ:ADI – Free Report) by 1.8% in the 1st quarter, according to the company in its most recent Form 13F filing with the Securities & Exchange Commission. The fund owned 80,250 shares of the semiconductor company's stock after purchasing an additional 1,405 shares […]",
      "summary": "Baker Chad R increased its holdings in shares of Analog Devices, Inc. (NASDAQ:ADI – Free Report) by 1.8% in the 1st quarter, according to the company in its most recent Form 13F filing with the Securities & Exchange Commission. The fund owned 80,250 shares of the semiconductor company's stock after purchasing an additional 1,405 shares […]\n\n\nThe post \nAnalog Devices, Inc. (NASDAQ:ADI) Shares Bought by Baker Chad R\n first appeared on \nDaily Political\n.",
      "rights": "dailypolitical.com",
      "rank": 793836,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Patrick Bannon",
      "media": "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/Analog_devices_logo.jpg&w=240&h=240&zc=2",
      "is_opinion": false,
      "twitter_account": "@MarketBeatCom",
      "_score": null,
      "_id": "515744a9670dcf09b86b94bf75d9314b"
    },
    {
      "title": "Schwarz Dygos Wheeler Investment Advisors LLC Buys New Position in Dimensional Core Fixed Income ETF (NYSEARCA:DFCF)",
      "author": "Patrick Bannon",
      "published_date": "2023-07-14 22:52:44",
      "published_date_precision": "timezone unknown",
      "link": "https://www.dailypolitical.com/2023/07/14/schwarz-dygos-wheeler-investment-advisors-llc-buys-new-position-in-dimensional-core-fixed-income-etf-nysearcadfcf.html",
      "clean_url": "dailypolitical.com",
      "excerpt": "Schwarz Dygos Wheeler Investment Advisors LLC bought a new stake in Dimensional Core Fixed Income ETF (NYSEARCA:DFCF – Free Report) in the 1st quarter, according to the company in its most recent Form…",
      "summary": "Schwarz Dygos Wheeler Investment Advisors LLC bought a new stake in Dimensional Core Fixed Income ETF (\nNYSEARCA:DFCF\n – \nFree Report\n) in the 1st quarter, according to the company in its most recent Form 13F filing with the Securities and Exchange Commission. The fund bought 5,157 shares of the company's stock, valued at approximately ${'$'}219,000. \n\n\nSeveral other institutional investors have also recently added to or reduced their stakes in DFCF. Blume Capital Management Inc. acquired a new position in shares of Dimensional Core Fixed Income ETF during the 4th quarter valued at about ${'$'}25,000.",
      "rights": "dailypolitical.com",
      "rank": 793836,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Patrick Bannon",
      "media": "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/dimensional-core-fixed-income-etf-logo.png?v=20220706142039&w=240&h=240&zc=2",
      "is_opinion": false,
      "twitter_account": "@RatingsNetwork",
      "_score": null,
      "_id": "bb908c78c15c45e27810f233581eb05c"
    },
    {
      "title": "Wm Morrison Supermarkets (OTCMKTS:MRWSY) Stock Crosses Above 200 Day Moving Average of ${'$'}19.24",
      "author": "Bryan LeMar",
      "published_date": "2023-07-14 22:52:42",
      "published_date_precision": "full",
      "link": "https://slatersentinel.com/news/2023/07/14/wm-morrison-supermarkets-otcmktsmrwsy-stock-crosses-above-200-day-moving-average-of-19-24.html",
      "clean_url": "slatersentinel.com",
      "excerpt": "Wm Morrison Supermarkets PLC (OTCMKTS:MRWSY – Get Free Report)'s share price crossed above its 200-day moving average during trading on Wednesday . The stock has a 200-day moving average of ${'$'}19.24 and…",
      "summary": "Wm Morrison Supermarkets PLC (\nOTCMKTS:MRWSY\n – \nGet Free Report\n)'s share price crossed above its 200-day moving average during trading on Wednesday . The stock has a 200-day moving average of ${'$'}19.24 and traded as high as ${'$'}19.24. Wm Morrison Supermarkets shares last traded at ${'$'}19.24, with a volume of 4,000 shares traded. \n\n\nWm Morrison Supermarkets Stock Up 0.4 %\n\n\nThe company has a debt-to-equity ratio of 0.45, a current ratio of 0.47 and a quick ratio of 0.24. The stock's 50-day simple moving average is ${'$'}19.",
      "rights": "slatersentinel.com",
      "rank": 776704,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Bryan LeMar",
      "media": "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/wm-morrison-supermarkets-plc-logo.jpg?v=20221109141529&w=240&h=240&zc=2",
      "is_opinion": false,
      "twitter_account": "@RatingsNetwork",
      "_score": null,
      "_id": "7c2826d43076f0972dc60eca0efc54d0"
    },
    {
      "title": "ProShares Ultra Bloomberg Crude Oil (NYSEARCA:UCO) Share Price Pass Above Two Hundred Day Moving Average of ${'$'}26.29",
      "author": "Terry King",
      "published_date": "2023-07-14 22:52:42",
      "published_date_precision": "full",
      "link": "https://slatersentinel.com/news/2023/07/14/proshares-ultra-bloomberg-crude-oil-nysearcauco-share-price-pass-above-two-hundred-day-moving-average-of-26-29.html",
      "clean_url": "slatersentinel.com",
      "excerpt": "ProShares Ultra Bloomberg Crude Oil (NYSEARCA:UCO – Get Free Report)'s share price crossed above its 200-day moving average during trading on Wednesday . The stock has a 200-day moving average of…",
      "summary": "ProShares Ultra Bloomberg Crude Oil (\nNYSEARCA:UCO\n – \nGet Free Report\n)'s share price crossed above its 200-day moving average during trading on Wednesday . The stock has a 200-day moving average of ${'$'}26.29 and traded as high as ${'$'}26.68. ProShares Ultra Bloomberg Crude Oil shares last traded at ${'$'}26.62, with a volume of 2,389,133 shares trading hands. \n\n\nProShares Ultra Bloomberg Crude Oil Stock Performance\n\n\nThe firm has a 50 day moving average price of ${'$'}23.91 and a two-hundred day moving average price of ${'$'}26.",
      "rights": "slatersentinel.com",
      "rank": 776704,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Terry King",
      "media": "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/proshares-ultra-bloomberg-crude-oil-logo.png?v=20210826120727&w=240&h=240&zc=2",
      "is_opinion": false,
      "twitter_account": "@RatingsNetwork",
      "_score": null,
      "_id": "afe3fb489aa77178b1f81e2077358e8e"
    },
    {
      "title": "Dorel Industries (TSE:DII.B) Share Price Crosses Above 200-Day Moving Average of ${'$'}4.57",
      "author": "Terry King",
      "published_date": "2023-07-14 22:52:42",
      "published_date_precision": "full",
      "link": "https://slatersentinel.com/news/2023/07/14/dorel-industries-tsedii-b-share-price-crosses-above-200-day-moving-average-of-4-57.html",
      "clean_url": "slatersentinel.com",
      "excerpt": "Dorel Industries Inc (TSE:DII.B – Get Free Report) shares crossed above its 200-day moving average during trading on Wednesday . The stock has a 200-day moving average of C${'$'}4.57 and traded as high as…",
      "summary": "Dorel Industries Inc (\nTSE:DII.B\n – \nGet Free Report\n) shares crossed above its 200-day moving average during trading on Wednesday . The stock has a 200-day moving average of C${'$'}4.57 and traded as high as C${'$'}5.01. Dorel Industries shares last traded at C${'$'}4.93, with a volume of 25,400 shares traded. \n\n\nDorel Industries Trading Up 1.8 %\n\n\nThe firm's 50 day simple moving average is C${'$'}4.44 and its 200-day simple moving average is C${'$'}4.58. The company has a quick ratio of 0.64, a current ratio of 1.68 and a debt-to-equity ratio of 160.",
      "rights": "slatersentinel.com",
      "rank": 776704,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Terry King",
      "media": "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/dorel-industries-inc-logo.gif&w=240&h=240&zc=2",
      "is_opinion": false,
      "twitter_account": "@RatingsNetwork",
      "_score": null,
      "_id": "dd9d71da3d7fe9717f1e3ee3ead0589b"
    },
    {
      "title": "BioLineRx (NASDAQ:BLRX) Stock Price Passes Above Two Hundred Day Moving Average of ${'$'}1.04",
      "author": "Amanda Harley",
      "published_date": "2023-07-14 22:52:42",
      "published_date_precision": "full",
      "link": "https://slatersentinel.com/news/2023/07/14/biolinerx-nasdaqblrx-stock-price-passes-above-two-hundred-day-moving-average-of-1-04.html",
      "clean_url": "slatersentinel.com",
      "excerpt": "BioLineRx Ltd. (NASDAQ:BLRX – Get Free Report)'s stock price passed above its two hundred day moving average during trading on Wednesday . The stock has a two hundred day moving average of ${'$'}1.04 and…",
      "summary": "BioLineRx Ltd. (\nNASDAQ:BLRX\n – \nGet Free Report\n)'s stock price passed above its two hundred day moving average during trading on Wednesday . The stock has a two hundred day moving average of ${'$'}1.04 and traded as high as ${'$'}1.75. BioLineRx shares last traded at ${'$'}1.69, with a volume of 273,123 shares trading hands. \n\n\nAnalyst Upgrades and Downgrades\n\n\nA number of brokerages recently issued reports on BLRX. HC Wainwright reissued a 'buy' rating on shares of BioLineRx in a report on Wednesday, March 22nd.",
      "rights": "slatersentinel.com",
      "rank": 776704,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Amanda Harley",
      "media": "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/bioline-rx-ltd-logo.jpg&w=240&h=240&zc=2",
      "is_opinion": false,
      "twitter_account": "@RatingsNetwork",
      "_score": null,
      "_id": "61ea56335e66edb20d9a8403298f62e6"
    },
    {
      "title": "InfuSystem (NYSEAMERICAN:INFU) Shares Pass Above Two Hundred Day Moving Average of ${'$'}0.00",
      "author": "Samantha Reynolds",
      "published_date": "2023-07-14 22:52:41",
      "published_date_precision": "full",
      "link": "https://dakotafinancialnews.com/2023/07/14/infusystem-nyseamericaninfu-shares-pass-above-two-hundred-day-moving-average-of-0-00.html",
      "clean_url": "dakotafinancialnews.com",
      "excerpt": "InfuSystem Holdings, Inc. (NYSEAMERICAN:INFU – Get Free Report) passed above its two hundred day moving average during trading on Wednesday . The stock has a two hundred day moving average of ${'$'}0.00…",
      "summary": "InfuSystem Holdings, Inc. (\nNYSEAMERICAN:INFU\n – \nGet Free Report\n) passed above its two hundred day moving average during trading on Wednesday . The stock has a two hundred day moving average of ${'$'}0.00 and traded as high as ${'$'}10.00. InfuSystem shares last traded at ${'$'}9.65, with a volume of 26,441 shares traded. \n\n\nAnalyst Upgrades and Downgrades\n\n\nSeparately, \nStockNews.com\n assumed coverage on InfuSystem in a research report on Thursday, May 18th. They issued a 'buy' rating on the stock.\n \nThe company has a debt-to-equity ratio of 0.",
      "rights": "dakotafinancialnews.com",
      "rank": 873414,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Samantha Reynolds",
      "media": "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/infusystem-holdings-inc-logo.png&w=240&h=240&zc=2",
      "is_opinion": false,
      "twitter_account": "@RatingsNetwork",
      "_score": null,
      "_id": "70c82c3ef4da1ed7e5139ef25348bada"
    },
    {
      "title": "First Trust Energy Infrastructure Fund (NYSE:FIF) Shares Cross Above Two Hundred Day Moving Average of ${'$'}14.55",
      "author": "Maddie Sorensen",
      "published_date": "2023-07-14 22:52:41",
      "published_date_precision": "full",
      "link": "https://dakotafinancialnews.com/2023/07/14/first-trust-energy-infrastructure-fund-nysefif-shares-cross-above-two-hundred-day-moving-average-of-14-55.html",
      "clean_url": "dakotafinancialnews.com",
      "excerpt": "First Trust Energy Infrastructure Fund (NYSE:FIF – Get Free Report) passed above its two hundred day moving average during trading on Wednesday . The stock has a two hundred day moving average of…",
      "summary": "First Trust Energy Infrastructure Fund (\nNYSE:FIF\n – \nGet Free Report\n) passed above its two hundred day moving average during trading on Wednesday . The stock has a two hundred day moving average of ${'$'}14.55 and traded as high as ${'$'}14.96. First Trust Energy Infrastructure Fund shares last traded at ${'$'}14.91, with a volume of 38,897 shares traded. \n\n\nFirst Trust Energy Infrastructure Fund Stock Down 1.1 %\n\n\nThe business has a 50 day simple moving average of ${'$'}14.41 and a 200-day simple moving average of ${'$'}14.",
      "rights": "dakotafinancialnews.com",
      "rank": 873414,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Maddie Sorensen",
      "media": "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/first-trust-energy-infrastructure-fund-logo.png?v=20220214075549&w=240&h=240&zc=2",
      "is_opinion": false,
      "twitter_account": "@RatingsNetwork",
      "_score": null,
      "_id": "43bff8071c0af2ff5594810921ab8672"
    },
    {
      "title": "5N Plus (TSE:VNP) Share Price Crosses Above 200 Day Moving Average of ${'$'}3.17",
      "author": "Maddie Sorensen",
      "published_date": "2023-07-14 22:52:41",
      "published_date_precision": "full",
      "link": "https://dakotafinancialnews.com/2023/07/14/5n-plus-tsevnp-share-price-crosses-above-200-day-moving-average-of-3-17.html",
      "clean_url": "dakotafinancialnews.com",
      "excerpt": "Shares of 5N Plus Inc. (TSE:VNP – Get Free Report) passed above its 200-day moving average during trading on Wednesday . The stock has a 200-day moving average of C${'$'}3.17 and traded as high as C${'$'}3.80.…",
      "summary": "Shares of 5N Plus Inc. (\nTSE:VNP\n – \nGet Free Report\n) passed above its 200-day moving average during trading on Wednesday . The stock has a 200-day moving average of C${'$'}3.17 and traded as high as C${'$'}3.80. 5N Plus shares last traded at C${'$'}3.65, with a volume of 100,804 shares trading hands. \n\n\nAnalysts Set New Price Targets\n\n\nVNP has been the topic of a number of recent research reports. National Bankshares raised their target price on 5N Plus from C${'$'}4.00 to C${'$'}4.25 and gave the company an 'outperform' rating in a research note on Friday, May 5th.",
      "rights": "dakotafinancialnews.com",
      "rank": 873414,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Maddie Sorensen",
      "media": "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/5n-plus-logo.jpg&w=240&h=240&zc=2",
      "is_opinion": false,
      "twitter_account": "@MarketBeatCom",
      "_score": null,
      "_id": "e62d88eae8fd64f9d06211627fcb2d17"
    },
    {
      "title": "5N Plus (TSE:VNP) Stock Crosses Above 200 Day Moving Average of ${'$'}3.17",
      "author": "Christopher Mengel",
      "published_date": "2023-07-14 22:52:41",
      "published_date_precision": "full",
      "link": "https://www.modernreaders.com/news/2023/07/14/5n-plus-tsevnp-stock-crosses-above-200-day-moving-average-of-3-17.html",
      "clean_url": "modernreaders.com",
      "excerpt": "5N Plus Inc. (TSE:VNP – Get Free Report)'s stock price passed above its two hundred day moving average during trading on Wednesday . The stock has a two hundred day moving average of C${'$'}3.17 and traded…",
      "summary": "5N Plus Inc. (\nTSE:VNP\n – \nGet Free Report\n)'s stock price passed above its two hundred day moving average during trading on Wednesday . The stock has a two hundred day moving average of C${'$'}3.17 and traded as high as C${'$'}3.80. 5N Plus shares last traded at C${'$'}3.65, with a volume of 100,804 shares. \n\n\nAnalysts Set New Price Targets\n\n\nA number of research analysts recently issued reports on VNP shares. National Bankshares boosted their price target on 5N Plus from C${'$'}4.00 to C${'$'}4.25 and gave the company an 'outperform' rating in a report on Friday, May 5th.",
      "rights": "modernreaders.com",
      "rank": 448265,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Christopher Mengel",
      "media": "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/5n-plus-logo.jpg&w=240&h=240&zc=2",
      "is_opinion": false,
      "twitter_account": "@MarketBeatCom",
      "_score": null,
      "_id": "7a978ba07840866c51f1867cef536338"
    },
    {
      "title": "Nikki Haley raises ${'$'}7.3 million in second quarter",
      "author": "Arun Kumar",
      "published_date": "2023-07-14 22:52:36",
      "published_date_precision": "timezone unknown",
      "link": "https://www.americanbazaaronline.com/2023/07/14/nikki-haley-raises-7-3-million-in-second-quarter-454267/",
      "clean_url": "americanbazaaronline.com",
      "excerpt": "Haley's campaign says voters want their next president to provide a vision for a strong and proud America Despite polling much lower than her two major rivals, former President Donald Trump and…",
      "summary": "Haley's campaign says voters want their next president to provide a vision for a strong and proud America\n\n\nDespite polling much lower than her two major rivals, former President Donald Trump and Florida Governor Ron DeSantis, Indian American Republican presidential candidate Nikki Haley raised ${'$'}7.3 million in the second quarter of 2023.\n\n\nHaley, the first Indian American to get a cabinet rank as US ambassador to UN under Trump, has raised ${'$'}15.6 million since launching her run, according to her campaign.",
      "rights": "americanbazaaronline.com",
      "rank": 78753,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Arun Kumar",
      "media": "https://www.americanbazaaronline.com/wp-content/uploads/2023/05/Nikki-Haley.jpg",
      "is_opinion": false,
      "twitter_account": "@ambazaarmag",
      "_score": null,
      "_id": "df03d4cf2b797ae222b906120a496760"
    },
    {
      "title": "Trung Quốc mất ngôi vị nước xuất khẩu nhiều nhất sang Mỹ, báo hiệu kinh tế toàn cầu thay đổi",
      "author": "Bảo Hà",
      "published_date": "2023-07-14 22:52:30",
      "published_date_precision": "full",
      "link": "https://vietgiaitri.com/trung-quoc-mat-ngoi-vi-nuoc-xuat-khau-nhieu-nhat-sang-my-bao-hieu-kinh-te-toan-cau-thay-doi-20230715i6944631/",
      "clean_url": "vietgiaitri.com",
      "excerpt": "Michael Burns, một đối tác quản lý tại Murray Hill Group, một công ty đầu tư tập trung vào chuỗi cung ứng, lý giải: Đó không phải là tình trạng phi toàn cầu hóa. Đây là giai đoạn tiếp theo của quá…",
      "summary": "Xu thế này báo hiệu giai đoạn tiếp theo của quá trình toàn cầu hóa tập trung vào các mạng lưới khu vực.\n \n \n \n \nADVERTISEMENT\n \n \n \n \nCảng hàng hóa Los Angeles\n, \nbang California\n, Mỹ. Ảnh minh họa: AFP/TTXVN\n \nTheo một bài đăng mới của ông Luis Torres – một nhà kinh tế kinh doanh cấp cao tại Ngân hàng \nDự trữ Liên bang Dallas\n (Mỹ), Mexico một lần nữa củng cố vị trí là đối tác thương mại hàng đầu của Mỹ, với 263 tỷ USD hàng hóa được giao dịch giữa hai nước trong 4 tháng đầu năm nay. Thương mại với Mexico chiếm 15,4% \nhàng hóa xuất khẩu\n và \nnhập khẩu\n của Mỹ, vượt xa tổng \nkim ngạch thương mại\n của Mỹ với Canada và \nTrung Quốc\n, lần lượt là 15,2% và 12%.",
      "rights": "vietgiaitri.com",
      "rank": 83978,
      "topic": "entertainment",
      "country": "VN",
      "language": "vi",
      "authors": "BẢO HÀ",
      "media": "https://i.vietgiaitri.com/2023/7/15/trung-quoc-mat-ngoi-vi-nuoc-xuat-khau-nhieu-nhat-sang-my-bao-hieu-kinh-te-toan-cau-thay-doi-442a9-6944631_default.webp",
      "is_opinion": false,
      "twitter_account": "@vietgiaitrinews",
      "_score": null,
      "_id": "14afdceacc7f65221c5db97095bcc767"
    },
    {
      "title": "وزارة العمل تعلن عن فرص عمل جديدة للشباب",
      "author": "جريدة الدستور",
      "published_date": "2023-07-14 22:52:30",
      "published_date_precision": "timezone unknown",
      "link": "https://www.dostor.org/4448972",
      "clean_url": "dostor.org",
      "excerpt": null,
      "summary": "",
      "rights": "Copyright(c) dostor.org",
      "rank": 66935,
      "topic": "news",
      "country": "EG",
      "language": "ar",
      "authors": "جريدة الدستور",
      "media": "https://www.dostor.org/UploadCache/libfiles/400/2/600x338o/29.jpg",
      "is_opinion": false,
      "twitter_account": "@dostor24_",
      "_score": null,
      "_id": "08605244eaf27d89aeb68a6e0f2589c4"
    },
    {
      "title": "Jared Kushner is reportedly testifying in the investigation into Trump and the Jan. 6 riots",
      "author": "Sammy Edwards",
      "published_date": "2023-07-14 22:52:26",
      "published_date_precision": "timezone unknown",
      "link": "https://shepherdgazette.com/jared-kushner-is-reportedly-testifying-in-the-investigation-into-trump-and-the-jan-6-riots/",
      "clean_url": "shepherdgazette.com",
      "excerpt": "By Madeline Halpert BBC News, New York 2 hours ago image source, Getty Images According to US media reports, former President Donald Trump's son-in-law Jared Kushner has appeared before a federal…",
      "summary": "By Madeline Halpert\n\n\nBBC News, New York\n\n\n\n\n2 hours ago\n\n\nimage source, \nGetty Images\n\n\nAccording to US media reports, former President Donald Trump's son-in-law Jared Kushner has appeared before a federal grand jury investigating Mr Trump's efforts to overturn the 2020 election. \n\n\nA special counsel for the Justice Department is investigating Mr Trump's actions in the run-up to the 2021 Capitol riots. \n\n\nThe grand jury asked whether Mr Trump admitted at the time that he lost the election, the New York Times reported.",
      "rights": "shepherdgazette.com",
      "rank": 534955,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Sammy Edwards",
      "media": "https://shepherdgazette.s3.amazonaws.com/wp-content/uploads/2023/07/14105154/130384307_gettyimages-1417349511-800x450.jpg",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "2b9ff185ae508d50e9a4e5eaaf508890"
    },
    {
      "title": "ClimateTV LIVE at 1PM ET – CLINTEL Exposes The Frozen Climate Views of the IPCC",
      "author": "Anthony Watts",
      "published_date": "2023-07-14 22:52:18",
      "published_date_precision": "timezone unknown",
      "link": "https://wattsupwiththat.com/2023/07/14/climatetv-live-at-1pm-et-clintel-exposes-the-frozen-climate-views-of-the-ipcc/",
      "clean_url": "wattsupwiththat.com",
      "excerpt": "The International Panel on Climate Change's (IPCC) sixth assessment report serves as the justification for many politicians to try and pass increasingly restrictive laws on society in the name of…",
      "summary": "The International Panel on Climate Change's (IPCC) sixth assessment report serves as the justification for many politicians to try and pass increasingly restrictive laws on society in the name of climate change. However, Andy May of the Climate Intelligence Foundation (CLINTEL) found many problems with the IPCC's sixth assessment report. It made numerous false assumptions and flawed assessments, while ignoring facts and research that is should have considered in its report. May also found that The IPCC erred in its comparisons of present data with proxy data for past climate conditions, make flawed assumptions about climate sensitivity and emissions, and unjustifiably assumed nature plays not significant role in climate change.",
      "rights": "wattsupwiththat.com",
      "rank": 9193,
      "topic": "news",
      "country": "US",
      "language": "en",
      "authors": "Anthony Watts",
      "media": "https://149366104.v2.pressablecdn.com/wp-content/uploads/2020/12/wuwt-logo.jpg",
      "is_opinion": false,
      "twitter_account": "@wattsupwiththat",
      "_score": null,
      "_id": "63a09320f5e8b1d5fedc9858d739a05f"
    },
    {
      "title": "Những ngày bận rộn của Thổ Nhĩ Kỳ tại hội nghị thượng đỉnh NATO",
      "author": "Hà Linh",
      "published_date": "2023-07-14 22:52:13",
      "published_date_precision": "full",
      "link": "https://vietgiaitri.com/nhung-ngay-ban-ron-cua-tho-nhi-ky-tai-hoi-nghi-thuong-dinh-nato-20230715i6944629/",
      "clean_url": "vietgiaitri.com",
      "excerpt": "Động thái Thổ Nhĩ Kỳ bật đèn xanh diễn ra trong bối cảnh Thụy Điển cam kết hỗ trợ cập nhật thỏa thuận thuế quan của Thổ Nhĩ Kỳ với Liên minh châu Âu (EU) và nguyện vọng của Ankara về việc công dân…",
      "summary": "Tại \nhội nghị thượng đỉnh\n của Tổ chức Hiệp ước Bắc Đại Tây Dương ( \nNATO\n) ở Litva từ 11-12/7, Thổ Nhĩ Kỳ đã vô cùng bận rộn với nhiều sự kiện được quan tâm như thỏa thuận F-16 với Mỹ, việc Thụy Điển muốn trở thành thành viên khối quân sự và vai trò của Ankara trong xung đột Nga-Ukraine.\n \n \n \n \nADVERTISEMENT\n \n \nTrong ảnh (từ trái sang): Tổng thống Thổ Nhĩ Kỳ \nRecep Tayyip Erdogan\n, Tổng Thư ký Tổ chức Hiệp ước Bắc Đại Tây Dương (NATO) \nJens Stoltenberg\n và Thủ tướng Thụy Điển Ulf Kristersson trong cuộc gặp trước thềm \nHội nghị thượng đỉnh NATO\n ở Vilnius (Litva) ngày 10/7.",
      "rights": "vietgiaitri.com",
      "rank": 83978,
      "topic": "entertainment",
      "country": "VN",
      "language": "vi",
      "authors": "HÀ LINH",
      "media": "https://i.vietgiaitri.com/2023/7/15/nhung-ngay-ban-ron-cua-tho-nhi-ky-tai-hoi-nghi-thuong-dinh-nato-b7b2b-6944629_default.webp",
      "is_opinion": false,
      "twitter_account": "@vietgiaitrinews",
      "_score": null,
      "_id": "2e925790eb6db1cf5bdb4c48130c5aae"
    },
    {
      "title": "Власти Грузии обвинили польского врача в том, что он хотел в ботинке вынести образец анализов Саакашвили",
      "author": "Авторизуйтесь",
      "published_date": "2023-07-14 22:52:07",
      "published_date_precision": "full",
      "link": "https://zn.ua/WORLD/vlasti-hruzii-obvinili-polskoho-vracha-v-tom-chto-on-khotel-v-botinke-vynesti-obrazets-analizov-saakashvili.html",
      "clean_url": "zn.ua",
      "excerpt": "Грузинские власти заявили, что польский врач пытался вынести образец анализов Саакашвили в ботинке",
      "summary": "",
      "rights": "zn.ua",
      "rank": 14390,
      "topic": "news",
      "country": "UA",
      "language": "ru",
      "authors": "Авторизуйтесь,Никита Ткаченко",
      "media": "https://zn.ua/img/article/5531/99_main-v1689375127.jpg",
      "is_opinion": false,
      "twitter_account": "@zn_ua",
      "_score": null,
      "_id": "78026a4e5f8615eae14a03e56436a547"
    },
    {
      "title": "Prima aparitie a lui Prigojin dupa marea revolta: in chiloti, pe un pat de campanie",
      "author": "Realitatea.NET",
      "published_date": "2023-07-14 22:52:04",
      "published_date_precision": "timezone unknown",
      "link": "https://www.realitatea.net/stiri/actual/prima-aparitie-a-lui-prigojin-dupa-marea-revolta-in-chiloti-pe-un-pat-de-campanie_64b1a7640e637c4811093a48",
      "clean_url": "realitatea.net",
      "excerpt": "O fotografie recenta distribuita pe retelele de socializare, cu o persoana care pare a fi Evgheni Prigojin a provocat un val de speculatii in randul expertilor si a opiniei publice internationale.",
      "summary": "Imaginea care a fost lansată pe canalele Telegram, înfățișează o persoană care seamănă cu liderul mercenarilor Wagner, Evgheni \nPrigojin\n, într-un cort de campanie, îmbrăcat sumar. Aceasta ar fi prima imagine după rebeliunea eșuată de la începutul lunii iunie și primul 'semn de viață' de la liderul Wagner.  Fotografia a alimentat suspiciunile cu privire la implicarea continuă a mercenarilor din Rusia în conflictele din întreaga lume.\nCu toate acestea, există incertitudine cu privire la veridicitatea imaginii, iar autoritățile nu au confirmat încă dacă persoana din fotografie este de fapt Prigojin sau o sosie a acestuia.",
      "rights": "realitatea.net",
      "rank": 37691,
      "topic": "news",
      "country": "RO",
      "language": "ro",
      "authors": "Realitatea.NET",
      "media": "https://media.realitatea.net/multimedia/image/202307/w1920/prigojin-chiloti_c94425d3e6.jpg",
      "is_opinion": false,
      "twitter_account": "@realitatea",
      "_score": null,
      "_id": "62fef9325171dee2711c4bc2fcda9e50"
    },
    {
      "title": "نزل ينقذ أخوه.. مصرع شقيقين غرقا فى مياه نهر النيل ببنها",
      "author": "إبراهيم خالد",
      "published_date": "2023-07-14 22:52:03",
      "published_date_precision": "timezone unknown",
      "link": "https://www.elbalad.news/5844773",
      "clean_url": "elbalad.news",
      "excerpt": "لقي شقيقين مصرعهما غرقا بمياه النيل بقرية دجوى التابعة لمركز شرطة بنها بمحافظة القليوبية، حيث حاول الأخ الأكبر إنقاذ شقيقه فور رؤيته له يغرق بالمياه، فقفز مسرعاً لانقاذه حتى لقى وفاته",
      "summary": "لقي شقيقين مصرعهما غرقا بمياه النيل بقرية دجوى التابعة لمركز شرطة بنها بمحافظة القليوبية.\n\nوجرى على الفور انتشال الجثتين بمساعدة الأهالى وحرر محضر بالواقعة وتولت الجهات المعنية التحقيق والتى صرحت بالدفن عقب ورود تقرير الصفة التشريحية، كما طلبت تحريات المباحث الجنائية حول الواقعة وملابستها وسؤال أهلية المتوفيين.\n\n\n\nتلقت الأجهزة الأمنية بالقليوبية اخطاراً من شرطة النجدة يفيد مصرع شقيقين غرقا بمياه النيل بمدينة بنها بمحافظة القليوبية.\n\n\n\nوعلى الفور انتقلت الأجهزة الأمنية لمكان الحادث وتبين مصرع كلا من \" احمد بلال، وشقيقه سيف بلال، مقيمين قرية دجوى دائرة مركز شرطة بنها.",
      "rights": "elbalad.news",
      "rank": 69336,
      "topic": "news",
      "country": "LB",
      "language": "ar",
      "authors": "إبراهيم خالد,صدى البلد",
      "media": "https://www.elbalad.news/UploadCache/libfiles/1014/1/600x338o/352.jpg",
      "is_opinion": false,
      "twitter_account": "@ElBaladOfficial",
      "_score": null,
      "_id": "61543142c43b349ff2b921c225e96c9f"
    },
    {
      "title": "6月末普惠小微贷款余额同比增长26.1%-中新网",
      "author": "作者 梁异",
      "published_date": "2023-07-14 22:52:02",
      "published_date_precision": "timezone unknown",
      "link": "http://www.chinanews.com/cj/2023/07-14/10043417.shtml",
      "clean_url": "chinanews.com",
      "excerpt": "2023-07-14 22:52:02 来源：央视网 作者：梁异 责任编辑：梁异 2023年07月14日 22:52 来源：央视网 央视网消息：国务院新闻办公室7月14日上午举行新闻发布会，介绍2023年上半年金融统计数据情况。中国人民银行副行长&#",
      "summary": "2023-07-14 22:52:02\n \n来源：\n央视网\n \n作者：梁异\n \n责任编辑：梁异\n \n \n 2023年07月14日 22:52　来源：央视网 \n \n \n \n　　央视网消息：国务院新闻办公室7月14日上午举行新闻发布会，介绍2023年上半年金融统计数据情况。中国人民银行副行长刘国强表示，从上半年数据看，总体保持平稳运行、流动性合理充裕、信贷结构持续优化、实体经济融资成本稳中有降、金融对经济的支持持续加强。\n \n　　6月末，制造业中长期贷款余额同比增长40.3%，比各项贷款增速高29.0个百分点；普惠小微贷款余额同比增长26.1%，比各项贷款增速高14.8个百分点。\n \n　　从利率看，推动实体经济融资成本稳中有降。上半年，新发放企业贷款加权平均利率为3.96%，比上年同期低25个基点。",
      "rights": "chinanews.com",
      "rank": 993,
      "topic": "finance",
      "country": "CN",
      "language": "cn",
      "authors": "chinanews,作者 梁异",
      "media": "http://i2.chinanews.com.cn/simg/ypt/2023/230714/54b1bdaa-0e6f-4f42-bca4-eff2e05a9d8b_zsite_sl.jpg",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "645f5c0bc9ca7a301f6173520709e3e6"
    },
    {
      "title": "『ラブライブ！サンシャイン!!』のスピンオフファンタジー作品のゲーム化『幻日のヨハネ -BLAZE in the DEEPBLUE-』試遊レポート。『ロックマン9』『ガンヴォルト』開発のインティ・クリエイツによる新作は、可愛いながらも歯ごたえしっかりの探索型2Dアクションゲーム【BitSummit Let's Go!!】",
      "author": "電ファミニコゲーマー",
      "published_date": "2023-07-14 22:52:00",
      "published_date_precision": "timezone unknown",
      "link": "https://headtopics.com/jp/1230212521125021106880-41217869",
      "clean_url": "headtopics.com",
      "excerpt": "『ラブライブ』まさかのメトロイドヴァニアに。話題のゲーム『幻日のヨハネ』を試遊してみた 公式スピンオフ作品『幻日のヨハネ』を良質な2Dアクションに定評のあるインティ・クリエイツがゲーム化。攻撃は仲間を召喚して行い、可愛いながらも歯ごたえはしっかり BitSummit",
      "summary": "7月14日より開催されているインディーゲームの祭典「Bitsummit Let's Go!!」にて、インティ・クリエイツは『ラブライブ！』シリーズの公式スピンオフ作品『幻日のヨハネ -SUNSHINE in the MIRROR-』をゲーム化した探索型2Dアクションゲーム『幻日のヨハネ -BLAZE in the DEEPBLUE-』を出展しており、同ブースにて試遊を提供している。 2023年7月14日 22:36 7月14日より開催されているインディーゲームの祭典「Bitsummit Let's Go!!」にて、インティ・クリエイツは 『ラブライブ！』 『幻日のヨハネ -SUNSHINE in the MIRROR-』 をゲーム化した探索型2Dアクションゲーム 『幻日のヨハネ -BLAZE in the DEEPBLUE-』 を出展しており、同ブースにて試遊を提供している。 『幻日のヨハネ -SUNSHINE in the...\n2023年7月14日 22:36 7月14日より開催されているインディーゲームの祭典「Bitsummit Let's Go!!」にて、インティ・クリエイツは",
      "rights": "headtopics.com",
      "rank": 25702,
      "topic": "news",
      "country": "US",
      "language": "ja",
      "authors": "電ファミニコゲーマー",
      "media": "https://i.headtopics.com/images/2023/7/14/denfaminicogame/1230212521125021903856-1230212521125021903856-1679851416196902912.webp",
      "is_opinion": false,
      "twitter_account": "@headtopicscom",
      "_score": null,
      "_id": "b01f73f97590a5935ecede12a4963c32"
    },
    {
      "title": "Green screen crash i vissa spel?",
      "author": "",
      "published_date": "2023-07-14 22:52:00",
      "published_date_precision": "timezone unknown",
      "link": "https://www.sweclockers.com/forum/trad/1693978-green-screen-crash-i-vissa-spel",
      "clean_url": "sweclockers.com",
      "excerpt": "Hej, köpte nyligen en ny dator och har funkat utmärkt att spela tex nya cod, cs osv.. Idag köpte jag RDR2 och skulle spela men det crashar och jag får en gre...",
      "summary": "Forum\n \n \nDatorer och system\n \n \nStationära datorer\n \n \nSupport och övrigt\n \n \nTråd\n \n \n \n \n \n \n \n \n \n \n \n \nHej, köpte nyligen en ny dator och har funkat utmärkt att spela tex nya cod, cs osv..\nIdag köpte jag RDR2 och skulle spela men det crashar och jag får en green screen och måste starta om dator på knappen? Händer varje gång jag börjar spela just RDR2, vad kan det bero på? Har provat uppdatera graphic card drivers.\n \n \n \n \n \n \nCitera flera\n \n \n \nCitera",
      "rights": "sweclockers.com",
      "rank": 91188,
      "topic": "tech",
      "country": "SE",
      "language": "sv",
      "authors": "",
      "media": "https://www.sweclockers.com/forum/trad/1693978/og-image",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "f03838aad4077a0e68709fbc71050bae"
    },
    {
      "title": "基地整備進む馬毛島の遺跡調査、再び延長　天候不良で７月２１日までに　鹿児島",
      "author": "南日本放送",
      "published_date": "2023-07-14 22:52:00",
      "published_date_precision": "timezone unknown",
      "link": "https://newsdig.tbs.co.jp/articles/-/604953",
      "clean_url": "tbs.co.jp",
      "excerpt": "自衛隊基地の整備とアメリカ軍の訓練移転が計画される西之表市・馬毛島での遺跡の発掘調査について、県教育委員会は、今月１５日までとしていた調査期間を２１日まで延長すると発表しました。馬毛島では、去年… (1ページ)",
      "summary": "自衛隊基地の整備とアメリカ軍の訓練移転が計画される西之表市・馬毛島での遺跡の発掘調査について、県教育委員会は、今月１５日までとしていた調査期間を２１日まで延長すると発表しました。\n\n馬毛島では、去年１０月に滑走路や駐機場の整備が予定されている島の中央部で、３万年以上前の旧石器時代のものとみられる石器などが見つかりました。\nこのため、防衛省は今年５月から県教委の勧告を受けて発掘調査を実施しています。\n\n調査期間は今月１５日まででしたが、県教委は「天候不良としけで作業に必要な日数が不足した」として、今月２１日まで延長すると発表しました。\n当初、発掘調査は今月１日までの予定でしたが、天候不良で延長されていて、期間の延長はこれで２度目です。\n\n防衛省によりますと、現在、馬毛島では滑走路の造成工事などが行われていて、調査の間は遺跡周辺での工事は中断されることになります。",
      "rights": "tbs.co.jp",
      "rank": 3539,
      "topic": "news",
      "country": "JP",
      "language": "ja",
      "authors": "TBS NEWS DIG,南日本放送",
      "media": "https://newsdig.ismcdn.jp/mwimgs/a/4/-/img_a47cceade5f75a654df5539d18244c5d157806.jpg",
      "is_opinion": false,
      "twitter_account": "@tbs_news",
      "_score": null,
      "_id": "b5c79fc745ab9f33d2c1c8c8df10d243"
    },
    {
      "title": "البنك الأهلي يلدغ فيوتشر بهدف «بامبو».. فيديو",
      "author": "البوابة نيوز",
      "published_date": "2023-07-14 22:51:53",
      "published_date_precision": "timezone unknown",
      "link": "https://www.albawabhnews.com/4839775",
      "clean_url": "albawabhnews.com",
      "excerpt": "حقق الفريق الأول لكرة القدم بنادي البنك الأهلي، فوزًا ثمينًا على نظيره فيوتشر بهدف للا شئ، خلال المباراة التي أقيمت بينهما مساء اليوم الجمعة، على ملعب استاد القاهرة الدولي، ضمن منافسات الجولة 34 والأخيرة من عمر مسابقة الدوري الممتاز لموسم 2022-2023.",
      "summary": "",
      "rights": "albawabhnews.com",
      "rank": 84804,
      "topic": "news",
      "country": "AE",
      "language": "ar",
      "authors": "البوابة نيوز",
      "media": "https://www.albawabhnews.com/UploadCache/libfiles/696/5/600x338o/554.jpeg",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "d6c60265871a1ff88e005ea6380f38d0"
    },
    {
      "title": "\"بكاء اللاعبين والمدرب\".. هبوط غزل المحلة رسميًا للدرجة الثانية (فيديو)",
      "author": "مصراوي",
      "published_date": "2023-07-14 22:51:52",
      "published_date_precision": "timezone unknown",
      "link": "https://www.masrawy.com/sports/sports_news/details/2023/7/14/2441403/-%D8%A8%D9%83%D8%A7%D8%A1-%D8%A7%D9%84%D9%84%D8%A7%D8%B9%D8%A8%D9%8A%D9%86-%D9%88%D8%A7%D9%84%D9%85%D8%AF%D8%B1%D8%A8-%D9%87%D8%A8%D9%88%D8%B7-%D8%BA%D8%B2%D9%84-%D8%A7%D9%84%D9%85%D8%AD%D9%84%D8%A9-%D8%B1%D8%B3%D9%85%D9%8A-%D8%A7-%D9%84%D9%84%D8%AF%D8%B1%D8%AC%D8%A9-%D8%A7%D9%84%D8%AB%D8%A7%D9%86%D9%8A%D8%A9-%D9%81%D9%8A%D8%AF%D9%8A%D9%88-",
      "clean_url": "masrawy.com",
      "excerpt": "بكاء اللاعبين والمدرب هبوط غزل المحلة رسمي ا للدرجة الثانية فيديو | مصراوى",
      "summary": "\"بكاء اللاعبين والمدرب\".. هبوط رسميًا للدرجة الثانية (فيديو)",
      "rights": "Masrawy-مصراوي",
      "rank": 37401,
      "topic": "sport",
      "country": "EG",
      "language": "ar",
      "authors": "مصراوي",
      "media": "https://media.gemini.media/img/large/2023/7/14/2023_7_14_22_51_21_965.JPG",
      "is_opinion": false,
      "twitter_account": "@Masrawy",
      "_score": null,
      "_id": "daeb0ea4ab2bb31887a9a0a815de4294"
    },
    {
      "title": "Jagged Alliance 3",
      "author": "Wykop Sp. Z O.O.",
      "published_date": "2023-07-14 22:51:40",
      "published_date_precision": "full",
      "link": "https://wykop.pl/link/7157121/jagged-alliance-3-recenzja-arhn-eu",
      "clean_url": "wykop.pl",
      "excerpt": "Nie mogę uwierzyć, że prawie 25 lat (!) czekałem na grę z serii Jagged Alliance, która nie będzie posysała po same uszy. Ale nareszcie się doczekałem. Jagged Al...",
      "summary": "Wybierz treści, które Cię interesują \n i zapisz jako Własną kategorię.\n \n \n \n \n \n \n \n \n \n \n \n \n \nNie mogę uwierzyć, że prawie 25 lat (!) czekałem na grę z serii Jagged Alliance, która nie będzie posysała po same uszy. Ale nareszcie się doczekałem. Jagged Alliance 3 to piękny prezent dla fanów tej klasycznej serii, choć obawiam się, że może rozminąć się z oczekiwaniami wielu współczesnych graczy\n \n \nipkis123\n z \ndodany: przed chwilą\n \n#\n#\n#\n#",
      "rights": "wykop.pl",
      "rank": 7730,
      "topic": "news",
      "country": "PL",
      "language": "pl",
      "authors": "Wykop Sp. Z O.O.",
      "media": "https://wykop.pl/cdn/c3397993/4609590b9605c4bb45d0750cbcf03101bff5c0a97693977d334b85e4bc99feaa.jpg",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "58f5642861bd4c3197025c8c620936ea"
    },
    {
      "title": "BYND Cannasoft stock drops on announced secondary offering",
      "author": "MarketWatch",
      "published_date": "2023-07-14 22:51:40",
      "published_date_precision": "full",
      "link": "https://flipboard.com/article/bynd-cannasoft-stock-drops-on-announced-secondary-offering/f-df722087b2%2Fmarketwatch.com",
      "clean_url": "flipboard.com",
      "excerpt": "MarketWatch - Shares of BYND Cannasoft Enterprises Inc. BCAN,-0.45% shares dropped in the extended session Friday after the cannabis business software company said …",
      "summary": "Sign up",
      "rights": "flipboard.com",
      "rank": 988,
      "topic": "news",
      "country": "US",
      "language": null,
      "authors": "MarketWatch,Wallace Witkowski",
      "media": "https://s.wsj.net/public/resources/MWimages/MW-GP644_MicroS_ZG_20180906154215.jpg",
      "is_opinion": false,
      "twitter_account": "@flipboard",
      "_score": null,
      "_id": "9239031e68d34961cdb32c4b0f89f633"
    },
    {
      "title": "আবার বৃষ্টি এলো",
      "author": "",
      "published_date": "2023-07-14 22:51:29",
      "published_date_precision": "timezone unknown",
      "link": "https://www.deshrupantor.com/ouside-calssroom/2023/07/15/438727",
      "clean_url": "deshrupantor.com",
      "excerpt": null,
      "summary": "অনেক দিন হলো বনে বৃষ্টি হয় না। আগে নিয়ম করেই বৃষ্টি হতো। আষাঢ়ে ঢল নামত পাহাড় বেয়ে। পশুপাখি, জীবজন্তু খুব আনন্দে ভিজত বৃষ্টিতে। ব্যাঙের ডাকাডাকি শুরু হয়ে যেত। মাছেরা লুটোপুটি করত বৃষ্টির পানিতে। এখন না হয় বৃষ্টি, না হয় ঢল। দুবছর আগের কথা। তখন",
      "rights": "Copyright: (C) deshrupantor",
      "rank": 905696,
      "topic": "news",
      "country": "BD",
      "language": "bn",
      "authors": "",
      "media": "",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "f1e3cc6698bb25c70df6a1d1916e09f2"
    },
    {
      "title": "রোজা ও পাতার গল্প",
      "author": "",
      "published_date": "2023-07-14 22:51:15",
      "published_date_precision": "timezone unknown",
      "link": "https://www.deshrupantor.com/ouside-calssroom/2023/07/15/438726",
      "clean_url": "deshrupantor.com",
      "excerpt": null,
      "summary": "রোজা সাত-এ পা দিয়েছে। এখনো ওর স্কুলে যাওয়া হয়নি। হবেইবা কেমন করে। মুখে অ, আ, ক, খ বুলি আওড়ানোর আগেই এক রাতে ওর মা ওকে একা করে চিরতরে চলে গেছেন। কত স্বপ্ন ছিল তার! অভাবের সংসারে খেয়ে না খেয়ে হলেও রোজাকে পড়াশোনা শিখিয়ে মানুষ করবেন। স্বামীর রোজগার",
      "rights": "Copyright: (C) deshrupantor",
      "rank": 905696,
      "topic": "news",
      "country": "BD",
      "language": "bn",
      "authors": "",
      "media": "",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "079d14acdaa253486711d07180d3809d"
    },
    {
      "title": "شقق الإسكان الاجتماعي، ما هي أسباب تأخر الاستعلام عن المتقدمين؟",
      "author": "منى حمزة",
      "published_date": "2023-07-14 22:51:14",
      "published_date_precision": "timezone unknown",
      "link": "https://www.vetogate.com/4927948",
      "clean_url": "vetogate.com",
      "excerpt": "كثير من الأسئلة والاستفسارات يرددها المواطنون المهتمون والراغبون بحجز شقق مشروعات وزارة الإسكان",
      "summary": "الجمعة 14/يوليو/2023 - 10:51 م\n\n 7/14/2023 10:51:14 PM \n\n\n\n\n\n\n\n\nشقق الإسكان الاجتماعي\n، كثير من الأسئلة والاستفسارات يرددها المواطنون المهتمون والراغبون بحجز شقق مشروعات وزارة الإسكان للمواطنين محدودي ومتوسطي الدخل، وخاصة بمشروع الإسكان الاجتماعي، ويتساءل البعض عن أسباب تأخر الاستعلام؟\nوأجاب صندوق الإسكان الاجتماعي والتمويل العقاري عن ذلك، مؤكدًا أن خطوة الاستعلام الميداني عن المتقدمين لحجز المشروع يتم بعد التأكد من استيفاء الأوراق والمستندات وجاهزية الشقق السكنية تمهيدا للتخصيص، أو بحسب ترتيب الأولوية للمتقدمين على المدن التى تشهد زيادة عدد المتقدمين عن الشقق المتاحة.",
      "rights": "vetogate.com",
      "rank": 124730,
      "topic": "news",
      "country": "EG",
      "language": "ar",
      "authors": "فيتو,منى حمزة",
      "media": "https://www.vetogate.com/UploadCache/libfiles/459/6/600x338o/41.png",
      "is_opinion": false,
      "twitter_account": "sync",
      "_score": null,
      "_id": "877233074f6af94e796707f2f9bb9205"
    },
    {
      "title": "Ohne einheitliche Linie",
      "author": "",
      "published_date": "2023-07-14 22:51:10",
      "published_date_precision": "timezone unknown",
      "link": "https://www.badisches-tagblatt.de/Nachrichten/Ohne-einheitliche-Linie-134114.html",
      "clean_url": "badisches-tagblatt.de",
      "excerpt": "Die Maske gehört wie der Haustürschlüssel weiter zu den Dingen, die man beim Konzertbesuch nicht daheim liegen lassen sollte. Zwar sind die meisten allgemeinen Corona-Schutzregeln am 3. April…",
      "summary": "Die Maske gehört wie der Haustürschlüssel weiter zu den Dingen, die man beim Konzertbesuch nicht daheim liegen lassen sollte. Zwar sind die meisten allgemeinen Corona-Schutzregeln am 3. April gefallen, die Maskenpflicht aber ist noch nicht überall vom Tisch. Das gilt auch und besonders dort, wo man Schulter an Schulter einer kulturellen Veranstaltung folgt oder sich Zeit nimmt für Kunst oder Literatur in Museen, Galerien oder Bibliotheken. \n \nDa nun die 3G-Kontrollen am Einlass weggefallen sind, hat auch das Virus wieder freien Eintritt.",
      "rights": "badisches-tagblatt.de",
      "rank": 324985,
      "topic": "news",
      "country": "DE",
      "language": "de",
      "authors": "",
      "media": "http://unternehmen.badisches-tagblatt.de/Layout/Custom/Favicon/BTPORTAL/favicon.ico",
      "is_opinion": false,
      "twitter_account": null,
      "_score": null,
      "_id": "df67f201d4ec11f16853c1787b6635f3"
    }
  ],
  "user_input": {
    "lang": null,
    "not_lang": null,
    "countries": null,
    "not_countries": null,
    "page": 1,
    "size": 50,
    "sources": null,
    "not_sources": [],
    "topic": null,
    "from": "2023-07-07 22:54:40"
  }
}"""